### PR TITLE
Enhancement: Fusion fix saver creation + minor Blender/Fusion logging tweaks

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

- Blender change logs to `debug` level in preparation for new publisher artist facing reports (note that it currently still uses the old publisher)
- [Fusion: Create Saver fix redeclaration of default_variants](https://github.com/ynput/OpenPype/commit/eadce2ce29f0df9da2a1b1c740e10bed4fa8a95e)
- [Fusion: Fix saver being created in incorrect state without saving directly after create](https://github.com/ynput/OpenPype/commit/5d221cf476000483a307fa212dd0d1b5ce0c618e)
- [Fusion: Allow reset frame range on render family](https://github.com/ynput/OpenPype/commit/56147ca26e5f994e02c4568d75be8bfcaf9fe2cb)
- [Fusion: Tweak logging level for artist-facing report](https://github.com/ynput/OpenPype/commit/2e6bdad7a0ede6c1445ef4e154df14cfbd355f40)

## Testing notes:

1. Test Blender publishing (even though only logging levels changed so it's a pretty safe change)
2. Test Fusion saver create + publisher
3. Test Fusion "Set Frame Range" on render family

### CODE REVIEW

**Comment by jakubjezek001** [comment]
It is reasonable to consider splitting this into two pull requests: one for Fusion and another for Blender.

**Comment by jakubjezek001** [comment]
> It is more than reasonable - yes, but I was working through 300 changed files between develop and our studio's branches haha that I just got too lazy when I saw these diffs. I can do it - but just know that I'll be doing it with a sad face. 🗡️❤️

I am sorry to make you sad. that was not an intention 😢

**Comment by BigRoy** [comment]
@jakubjezek001 @EmberLightVFX what's needed to get this through? :)

**Review by EmberLightVFX — APPROVED** [review]
Looks good to me :)

**Review by simonebarbieri — APPROVED** [review]
The Blender part looks good to me. No changes except to debug logs, and they all make sense.

The Fusion part looks good as well, code-wise, but I don't have experience at all with that, so it's better to wait for an opinion from @jakubjezek001

**Comment by BigRoy** [comment]
I suppose @EmberLightVFX tested the Fusion side of things?

**Review by jakubjezek001 — APPROVED** [review]
LGTM - turning a blind eye... ;)

**Pull request merged**
