### PR TITLE
Maya: fix error when exporting alembic cameras

### PR DESCRIPTION
**Pull request by friquette**
## Changelog Description
When exporting cameras in alembic, there's an ancestor relationship error in the root arguments. So we put the second root argument in a condition.
What do you think of this solution ?

## Additional info
Here's the error we got:
image

### CODE REVIEW

**Comment by BigRoy** [comment]
Could it be that your publish instance (the object set) contains both cameras and parent transforms, or camera shapes and their transforms?

Could you show your set members in the outliner. I suspect the issue is there because I can't reproduce it on my end.

This is what I'd expect:
image

**Comment by BigRoy** [comment]
Also note that your screenshot is using the old style publisher. Current `develop` uses the new style publisher. Would be good to confirm the issue there too.

**Comment by friquette** [comment]
> Could it be that your publish instance (the object set) contains both cameras and parent transforms, or camera shapes and their transforms?
> 
> Could you show your set members in the outliner. I suspect the issue is there because I can't reproduce it on my end.
> 
> This is what I'd expect: image

This is what our set looks like:
image
Our cameras are in the grp_cam group

**Comment by tokejepsen** [comment]
Can confirm that having a camera parented to a group and publishing the group works in latest `develop`, so cant reproduce the issue of this PR.

@friquette when you have a reproducible scene or steps, let us know and mark the PR ready for review.

**Comment by tokejepsen** [comment]
@friquette is this still needed?
If so, we'll need some testing notes to replicate the issue.

**Comment by mkolar** [comment]
@friquette we're closing this PR as it is now stale and can't be reproduced.

**Pull request closed without merging**
