### PR TITLE
Maya: Remove `shelf` class and shelf build on maya `userSetup.py`

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Remove shelf builder logic. It appeared to be unused and had bugs.

## Additional info

Bugs/unused:
- It referenced `self._null` even though it didn't exist there.
- Docstring mentioned it had an empty `build` method - it didn't; it ran a preset dict.
- It builds from `settings['maya'].get('project_shelf')` which is **not** an existing key in project settings.
- It used environment var `OPENPYPE_PROJECT_SCRIPTS` in the build but it's not set anywhere so will be confusing to anyone if it were to be run even (since it doesn't have settings you can't run it.)
- The whole shelf preset setup is weird with `exec` calls and could be potentially abused by someone savvy with ill intent.
- `addMenuItem` didn't set the icon if it were passed
- + a lot of cosmetic issues; code style doesn't match rest of the code, etc.

@mkolar Do you know of someone somewhere _potentially using this?_ It seemed originally coded by you but I have a feeling its ancient and now unused code.

## Testing notes:

1. Maya should launch and still work as expected.

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
Launches Maya successfully without any error and I have done some quick test with the publishing and so far so good. I also take a look at Openpype tool and open dialogs to see if it has registered and all look fine.
Code looks good for me too.
image

**Comment by mkolar** [comment]
Agreed. this has been used on some old productions to build custom shelfs and clearly a legacy bit.

We have a small conflict, but happy to merge when that is resolved.

**Comment by BigRoy** [comment]
@mkolar should be resolved now

**Review by tokejepsen — APPROVED** [review]
Tested in Maya 2023 successfully. Ready to merge.

**Review by antirotor — APPROVED** [review]

**Comment by BigRoy** [comment]
Yay, time for merging! 🚀

**Comment by mkolar** [comment]
Shame to not merge this even though technically it should not make it to OP anymore. @bradenjennings could you please port it to ayon-core, so we can merge both at the same time?

**Pull request merged**
