### PR TITLE
AYON Switch tool: Keep version after switch

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Keep version if only representation did change. The AYON variant of https://github.com/ynput/OpenPype/pull/4629

## Additional info
Modified a little OpenPype's version doc resolution which did not count with missing hero version and expected that container version has `"name"` if representation is not filled.

## Testing notes:
1. Load a subset with several representation(any host)
2. Set version that is not the last existing version.
3. Switch the subset representation using the scene inventory.
4. Version should not change to the latest.

### CODE REVIEW

**Comment by kalisp** [comment]
It fails (in Fusion) when changing repre:
image

**Comment by moonyuet** [comment]
It is not working from my side neither with similar error mentioned above.
```
Traceback (most recent call last):
  File "D:\kayla\OpenPype\openpype\tools\ayon_sceneinventory\switch_dialog\dialog.py", line 1173, in _on_accept
    self._trigger_switch()
  File "D:\kayla\OpenPype\openpype\tools\ayon_sceneinventory\switch_dialog\dialog.py", line 1237, in _trigger_switch
    self._switch_container(
  File "D:\kayla\OpenPype\openpype\tools\ayon_sceneinventory\switch_dialog\dialog.py", line 1328, in _switch_container
    repre_doc = repres_by_name[selected_representation]
KeyError: 'max'
```

**Comment by iLLiCiTiT** [comment]
> It fails (in Fusion) when changing repre:

Should be fixed.

**Review by kalisp — APPROVED** [review]
Now it works (tested in Fusion).

**Pull request merged**
