### PR TITLE
Publisher window as dialog

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Changing back Publisher window to QDialog.

## Additional info
The reasoning for changing it to `QWidget` was to avoid having window always on top, which `QDialog` might cause on it's own (even without AlwaysOnTop flag). But it was found out that using `QWidget` with `Window` flag did break window positioning for some DCCs and broke stylesheets for almost all of them, especially when parent was passed to init. The reason why that happens was not revealed.

At the same time there was random behavior in substance painter where the publisher tool was moved under substance without any user interaction, when parent was not passed in, and had broken stylesheets when parent was passed in.

This might again raise issues when a DCC opens dialog that is modal, it might show under publisher and block the process.

## Testing notes:
1. Publisher should show ok in all DCCs

- [x] Blender
- [x] Maya
- [x] Max
- [x] SPainter
- [x] Photoshop
- [x] Nuke
- [x] Resolve
- [x] Houdini
- [x] Fusion
- [x] Flame
- [ ] Harmony
- [ ] Celaction
- [x] After Effects
- [ ] UE

### CODE REVIEW

**Comment by LiborBatek** [comment]
Performed test in SP the ```Publisher``` window seems behaving ok in terms of focus and not being always ```on top``` but there is still that weird enlarging issue of the window present... not sure if related to this PR or if it should be ignored atm.

the UI progressively grows to the right of the screen infinitely
image

**Comment by LiborBatek** [comment]
When testing Photoshop, Im facing issue with ```context``` being lost...again not fully sure if connected to this PR

Screenshot 2024-01-29 102327

After trying to Save Im getting this error msg

```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.18.5\openpype\pipeline\create\context.py", line 2359, in _save_instance_changes
    creator.update_instances(update_list)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.18.5\openpype\hosts\photoshop\lib.py", line 32, in update_instances
    api.stub().imprint(created_inst.get("instance_id"),
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.18.5\openpype\hosts\photoshop\api\launch_logic.py", line 102, in stub
    raise ConnectionNotEstablishedYet("Connection is not created yet")
openpype.hosts.photoshop.api.launch_logic.ConnectionNotEstablishedYet: Connection is not created yet
```

**Comment by LiborBatek** [comment]
Task linked: [OP-7725 Substance - Workfile UI under the main UI](https://app.clickup.com/t/6658547/OP-7725)

**Comment by iLLiCiTiT** [comment]
> the UI progressively grows to the right of the screen infinitely

Unrelated to this PR.

> After trying to Save Im getting this error msg

Unrelated to PR, @kalisp please contact @LiborBatek and take a look.

**Comment by LiborBatek** [comment]
@MustafaJafar maybe could u help with testing too (Houdini and maybe more) ?

**Review by MustafaJafar — APPROVED** [review]
Tested in Houdini. It worked fine for me.

**Pull request merged**
