### PR TITLE
OPv3: Add filters in launcher

### PR DESCRIPTION
**Pull request by ClementHector**
Adding a widget in the launcher to filter assets and tasks: https://github.com/pypeclub/OpenPype/issues/2380

### CODE REVIEW

**Comment by ClementHector** [comment]
Is it possible to pass it in draft PR?

**Comment by m-u-r-p-h-y** [comment]
I was trying to test this one, but run into issues with merging this branch. with the current code base. Maybe it is just my setup on my machine but asking if it is still relevant and I should continue reviewing it :)

**Comment by Minkiu** [comment]
Hello @ClementHector  is this something you still want? Is ready to be reviewed?

**Comment by ClementHector** [comment]
I'm closing this, because we are now using the launcher from ftrack.

**Pull request closed without merging**
