### PR TITLE
'NumberAttrWidget' shows 'Multiselection' label on multiselection

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Attribute definition widget 'NumberAttrWidget' shows `< Multiselection >`  label on multiselection.

## Additional info
I've tried multiple different approaches and after few fails when overriding `paintEvent`, changing `QLineEdit` in spinboxes and some others, I found out the easiest is to show different QLineEdit which is clickable.

## Testing notes:
1. Create 2 instances with number inputs
2. Change value of first to different value from second instance
3. Select both
4. Label `< Multiselection >` should show and if you click on it it should show one of the values there

Resolves https://github.com/ynput/OpenPype/issues/5790

### CODE REVIEW

**Review by BigRoy — CHANGES_REQUESTED** [review]
When clicking into the multiselection field it shows the value but will also automatically _assign_ the value to all instances - not sure the a good workaround would be for that but it was a bit unexpected that just clicking into it would also be updating the value for the different instances that I had selected.

Note that it only seems to happen if the value in the field is **not** the default value. So change both from the default value to something different - then select both instances, click <Multiselect> then click left hand side on one of the instances - the values have updated for both. However if the entry shown on click is the default value somehow it doesn't update?

**Comment by iLLiCiTiT** [comment]
It should not change the instance values until you explicitly change the values in widget and when the widget looses focus the multiselection label is showed back again.

**Review by BigRoy — APPROVED** [review]
Works as intended. Nice work!

I really like that pressing ENTER when in the field but you didn't change the value that it'd still set it - so you don't **need** to change the value you can also press enter! :)

**Comment by iLLiCiTiT** [comment]
> I really like that pressing ENTER when in the field but you didn't change the value that it'd still set it - so you don't need to change the value you can also press enter! :)

That works? Or is it request?

**Comment by BigRoy** [comment]
> That works? Or is it request?

That works, yes.

**Pull request merged**
