### PR TITLE
Houdini: Refactor Extractors to use ROP input dependency ordering

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Render ROPs in the order of the Input Dependencies in the ROP networks.

## Additional info

Examples:

sorted_rops

image

---

Note: Due to this now being a Context Plug-in this will not mark any of its logs related to an instance. It might be nice @iLLiCiTiT to have a mechanism during publishing to be able to e.g. do:

```python
class Plugin(pyblish.api.ContextPlugin):
    def process(self, context):
        with context.as_instance(instance):
            self.log.info(f"Log for {instance}")
            raise PublishValidationError(f"Error for {instance}")
```

So that for an artist we could still show logs/errors as related to a particular instance.
However, since that's currently not possible logs and errors will be shown on the Instance.

---

This currently does not alter anything for Deadline submissions - there is no defined "ordering" or "job dependencies" in that area that uses this sorting. That's to be implemented.

## Testing notes:

1. Launch Houdini
2. Publish all types of instances; with and without input dependencies in /out

### CODE REVIEW

**Comment by MustafaJafar** [comment]
I believe this PR shares similar bugs with the publish button.
this method `rop.inputDependencies()` has problems with Karma and HDA instances as follows 
- `Karma` is a subnetwork, and the method retrieves another node inside the subnetwork. 
    ```
    DEBUG: Ignoring instance karma_ropTest as it is marked for farm rendering...
    DEBUG: Defined rendering order:
    DEBUG:     0. /out/karma_ropTest/lopnet/rop_usdrender
    DEBUG:     1. /out/vdbcacheTest
    DEBUG:     2. /out/pointcacheBgeoTest
    ```
- `HDA` doesn't have that method. 
    ```
    Traceback (most recent call last):
      File "E:\Ynput\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
        runner(*args)
      File "E:\Ynput\OpenPype\openpype\hosts\houdini\plugins\publish\extract_rop.py", line 53, in process
        sorted_rops = get_sorted_rops(rop_nodes)
      File "E:\Ynput\OpenPype\openpype\hosts\houdini\api\lib.py", line 1057, in get_sorted_rops
        in enumerate(rop.inputDependencies())
    AttributeError: 'ObjNode' object has no attribute 'inputDependencies'
    ```

for the publish button I didn't need the dependencies in the correct order so my simple solution to check the inputs was sufficient https://github.com/ynput/OpenPype/pull/5891 

I can tweak my solution a little to return the correct order. 
```python
import hou

def find_rop_inputs_chain(node):
    """Find rop inputs chain.
    This function retrieves input nodes and their inputs recursively.
    Arguments:
        node (hou.Node) The node at which the find function starts.
    Returns:
        list the paths of all input nodes.
    """

    all_input_nodes = []
    input_nodes = node.inputs()
    for input_node in input_nodes:
        all_input_nodes += find_rop_inputs_chain(input_node)
        all_input_nodes.append(input_node.path())
        

    return all_input_nodes
    
    
node = hou.node('/out/staticMeshObjTest')
all_nodes = find_rop_inputs_chain(node)
all_nodes.append(node.path())
print(all_nodes)
```
test 1 
```python
['/out/usdTest', '/out/reviewTest', '/out/staticMeshSopTest', '/out/staticMeshObjTest']
```

image


test 2 
```python
['/out/pointcacheABCTest',
 '/out/mantra_ropTest',
 '/out/usdTest', 
'/out/karma_ropTest', 
'/out/vdbcacheTest', 
'/out/cameraTest', 
'/out/pointcacheBgeoTest', 
'/out/imagesequenceTest', 
'/out/reviewTest', 
'/out/staticMeshSopTest', 
'/out/staticMeshObjTest']
```

image

**Comment by BigRoy** [comment]
@MustafaJafar I'm pretty sure your function will fail for these cases:

image

Because in that case there will be rops where a rop will be closer to the 'final' node you're getting the inputs for than for another ROP - meaning you'd still need to sort them if you want to detect the order for all ROPs intead of just iterating inputs for _one_ ROP. You'd still need to identify the full ordering for each, right?

Also, be wary with that function - it is possible in the out network to create cyclic dependencies (not sure why you'd do that) but it'd make your function basically recurse itself over and over.


> * `HDA` doesn't have that method.
>       ```
>       Traceback (most recent call last):
>         File "E:\Ynput\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, in __explicit_process
>           runner(*args)
>         File "E:\Ynput\OpenPype\openpype\hosts\houdini\plugins\publish\extract_rop.py", line 53, in process
>           sorted_rops = get_sorted_rops(rop_nodes)
>         File "E:\Ynput\OpenPype\openpype\hosts\houdini\api\lib.py", line 1057, in get_sorted_rops
>           in enumerate(rop.inputDependencies())
>       AttributeError: 'ObjNode' object has no attribute 'inputDependencies'
>       ```

What the hell? But... could you even `.render()` that? I wonder how Deadline deals with a dependency like that.

Deadline's code is in `repository\submission\Houdini\Main\SubmitDeadlineRop.py` which does also seem to indeed iterate `.inputs()` but because of that also has to handle very specific cases, like from a `switch` node pick only the active input, etc.
As can be seen there, that will grow complicated quickly. Also, Fetch nodes then get special treatment as well. Anything that is not a ROP and not a Fetch seems to be discard/ignored, so likely the `ObjNode` you're hitting issues with here would by Deadline just be ignored and only considered if it were a RopNode.

> * `Karma` is a subnetwork, and the method retrieves another node inside the subnetwork.
>       ```
>       DEBUG: Ignoring instance karma_ropTest as it is marked for farm rendering...
>       DEBUG: Defined rendering order:
>       DEBUG:     0. /out/karma_ropTest/lopnet/rop_usdrender
>       DEBUG:     1. /out/vdbcacheTest
>       DEBUG:     2. /out/pointcacheBgeoTest
>       ```

I mean, it's not 'wrong' but it does feel a bit unexpected. And it would the rop to instance code I wrote for this PR at least.

**Comment by moonyuet** [comment]
I also did some simple test in my side, the input ordering looks good but I do have some questions on the refactoring after looking at Mustafa's test. 
Do you think it's better idea to have the custom OP parameters (or a custom OP node, but it's not really for publishing but setting up and collecting custom data for publishing) for input dependency ordering? This is for just in case the users have relatively complex graph in their `/out` and the ROP extractors can't recognize the ordering.

**Comment by fabiaserra** [comment]
Repeating what I said here https://github.com/ynput/OpenPype/pull/5891#issuecomment-1812676450 and I will add some more info

> * `HDA` doesn't have that method.
>   `Traceback (most recent call last): File "E:\Ynput\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 527, `

You are looking at OBJ HDAs and not ROP HDAs. ROP HDAs do have that method and that's what we should be looking at supporting if we want an alternative to the Deadline Submission ROP. We don't need dependency graph evaluation or farm submission on the OBJ context!

**Comment by mkolar** [comment]
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be re-created to target one of those.

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-core](https://github.com/ynput/ayon-core) or the host addon repository once it's up.

**Pull request closed without merging**
