### PR TITLE
General: Push to studio library

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Added simple action to push version to a library project.

## Description
Added action "Push to library project" which can run only on one version at a time. The action is triggering new tool "push to project" which fake's integration. This is first iteration over the feature as prove of concept which means "it is not perfect". The premise is to be able push version (and asset) to library project with representations that are integrated as would be during publishing. The tool gives user option to select context to which is version pushed, what variant will be used for subset name and ability to create new asset. This can cause issues as the creation of asset is not propagated to project managers (ftrack, shotgrid, kitsu, ...). Also there is missing review or thumbnail.

Added `LoadError` to show custom message to a user when loading fails.

## Additional info
~~- User can trigger push to different project only once and any crash will cause that he must trigger the action again. At this moment it is because the overlay is showing "result" of the process and give option to only close the window, maybe "Try again" button could be added -> showed only when process fails?~~ Added `"Try again"` button if process fails with known error.
- Maybe add settings to be able disable the action -> not sure if all studios would like to use it?

### Unrelated info
- Discovered small issue in loader, I've found out is that loaders can't define full name of icon in font awesome library, only icons starting with `fa.`.

## Screenshot
image

## Testing notes:
1. Open Loader/Library loader
2. Select an asset which has published versions
3. Select a version with representations
4. Right click on the version a hit `"Push to Library project"`
5. New process should start with UI tool
6. Select library project where to publish
7. Select asset
*8. Select task (only if `"New asset name"` is empty)
9. Fill/Remove `"New asset name"` value
    - If is filled new asset is created and selected asset is used as parent
    - Selected asset is used as target asset if not filled
10. Check/fill variant for subset name
*11. Add comment
12. Hit `Publish`
13. Wait until process finishes

### CODE REVIEW

**Review by jakubjezek001 — APPROVED** [review]
It works. But it was having issue with Comment input field
```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype3\openpype\lib\events.py", line 189, in process_event
    callback(event)
  File "C:\CODE\__PYPE\OpenPype3\openpype\tools\push_to_project\window.py", line 703, in _on_controller_comment_change
    comment = event["comment"]
  File "C:\CODE\__PYPE\OpenPype3\openpype\lib\events.py", line 234, in __getitem__
    return self._data[key]
KeyError: 'comment'
```

**Comment by jakubjezek001** [comment]
Task linked: [OP-3930 Publish to Studio Library](https://app.clickup.com/t/6658547/OP-3930)

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
comment is not published into library project

**Review by jakubjezek001 — APPROVED** [review]

**Comment by iLLiCiTiT** [comment]
This is not in "perfect" state but we need some feedback from client to make enhancements.

**Comment by BigRoy** [comment]
This PR has broken the Loader tool in Houdini:

afbeelding

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 419, in show_loader
    "loader", parent, use_context=use_context
  File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 394, in show_tool_by_name
    cls.helper.show_tool_by_name(tool_name, parent, *args, **kwargs)
  File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 345, in show_tool_by_name
    self.show_loader(parent, *args, **kwargs)
  File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 89, in show_loader
    loader_tool = self.get_loader_tool(parent)
  File "S:\openpype\OpenPype\openpype\tools\utils\host_tools.py", line 76, in get_loader_tool
    from openpype.tools.loader import LoaderWindow
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.435\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "S:\openpype\OpenPype\openpype\tools\loader\__init__.py", line 1, in <module>
    from .app import (
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.435\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "S:\openpype\OpenPype\openpype\tools\loader\app.py", line 19, in <module>
    from .widgets import (
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.435\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "S:\openpype\OpenPype\openpype\tools\loader\widgets.py", line 23, in <module>
    from openpype.pipeline.load import (
ImportError: cannot import name 'LoadError' from 'openpype.pipeline.load' (S:\openpype\OpenPype\openpype\pipeline\load\__init__.py)
```

This happens on OpenPype > Load..

**Pull request merged**
