### PR TITLE
Blender: fix import workfile all families

### PR DESCRIPTION
**Pull request by Tilix4**
## Brief description
Having this feature related to workfile available for any family is absurd.

### CODE REVIEW

**Review by moonyuet — CHANGES_REQUESTED** [review]
EDIT: Maybe you need to register in somewhere to make the import blend and append blend loader to show up, or use the original code.
image

**Comment by moonyuet** [comment]
> EDITED: maybe the "workfile" also needs somewhere to load it right.
image

**Comment by Tilix4** [comment]
> EDIT: Maybe you need to register in somewhere to make the import blend and append blend loader to show up, or use the original code. image

I'm sorry, I don't get your review. Could you please explain a bit more?

**Comment by moonyuet** [comment]
> > EDIT: Maybe you need to register in somewhere to make the import blend and append blend loader to show up, or use the original code. image
> 
> I'm sorry, I don't get your review. Could you please explain a bit more?
when I was using your code with workfile added into families, the loader doesn't show the import option
But if I run the original code, it will be there.

**Comment by Tilix4** [comment]
> > > EDIT: Maybe you need to register in somewhere to make the import blend and append blend loader to show up, or use the original code. image
> > 
> > 
> > I'm sorry, I don't get your review. Could you please explain a bit more?
> 
> when I was using your code with workfile added into families, the loader doesn't show the import option But if I run the original code, it will be there.

Tell me if I'm wrong, but it is actually the point. You mustn't see the loader for families other than `workfile`. And in your example you seem to test exactly the case where it must be disabled, confirming the change works.

**Comment by moonyuet** [comment]
> > > > EDIT: Maybe you need to register in somewhere to make the import blend and append blend loader to show up, or use the original code. image
> > > 
> > > 
> > > I'm sorry, I don't get your review. Could you please explain a bit more?
> > 
> > 
> > when I was using your code with workfile added into families, the loader doesn't show the import option But if I run the original code, it will be there.
> 
> Tell me if I'm wrong, but it is actually the point. You mustn't see the loader for families other than `workfile`. And in your example you seem to test exactly the case where it must be disabled, confirming the change works.

ah i see. I misunderstand the intention of this PR and I resume my previous comment. If it is the case, i think you are right. It shouldn't load the workfile, instead there should be a family for raw blend scene included into the loader and the extractor for exporting the blend scene.

**Review by moonyuet — APPROVED** [review]

**Review by simonebarbieri — APPROVED** [review]

**Pull request merged**
