### PR TITLE
Tray AYON: Connection timeout and update validations

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Tray tool can validate if is required update of AYON bundle and asks to relogin if user credentials are not valid.

## Additional info
The validation happens once per 5 minutes. The credentials check happens withing it. It is still not possible to re-login when inside host and the validation happens only once a 5 minutes, but better than nothing. The update dialog is shown only in production or staging mode.

### Possible enhancements in this PR
Maybe we should show information dialog "Your credentials are not valid anymore. Please close all applications and login again." before the login dialog is showed.

## Testing notes:
Updates detection
1. Start tray in production
2. Change production bundle on server
3. Wait 5 minutes
4. An dialog with restart request should show up

Relogin
1. Start tray
2. Shotdown your server
3. After 5 minutes a login dialog should be shown

### CODE REVIEW

**Comment by BigRoy** [comment]
> Maybe we should show information dialog "Your credentials are not valid anymore. Please close all applications and login again." before the login dialog is showed.

Out of curiosity - when does this occur? Say someone leaves a scene open over the weekend, do they run into this?

---

Also, if say the artist 'ignores' that there's a new version available (like, can they cancel a restart?) does that mean that after another five minutes it directly starts showing the pop-up again? Or should it be a dialog that does something like "Remind me in `[ ]` (enter here) minutes." where the default is five so they are aware they will be notified.

Or is it that when 'ignored' once that you won't get notification about that version again?

**Comment by BigRoy** [comment]
> > Out of curiosity - when does this occur? Say someone leaves a scene open over the weekend, do they run into this?
> 
> not only over weekend but even leaving running DCC (Nuke for example) overnight and in the morning you want to continue working and you are suddenly stuck with a nonworking system unable to even save your scene.

Ah yes, that does sound critical - the way I understand this PR still doesn't solve that. It just tells you that your stuff is now broken?

**Comment by iLLiCiTiT** [comment]
> where the default is five so they are aware they will be notified.

Reused same dialog from OpenPype, will show after 5 minutes again. Won't change in this PR.

> not only over weekend but even leaving running DCC (Nuke for example) overnight and in the morning you want to continue working and you are suddenly stuck with a nonworking system unable to even save your scene.

Just to be sure, this won't be fixed by this PR.

**Comment by BigRoy** [comment]
> Reused same dialog from OpenPype, will show after 5 minutes again. Won't change in this PR.

I see - we have our OpenPype timer set _much higher_. I think four or six hours. Is this possible here too?

**Comment by iLLiCiTiT** [comment]
> I see - we have our OpenPype timer set much higher. I think four or six hours. Is this possible here too?

No, but I can add setting for that. In that case I should create another timer to check the valid credentials more often.

**Comment by LiborBatek** [comment]
@BigRoy  I can also think about occasions when user/artist just keep running Tray app for days without restarting it anytime...u need sort of check if new bundle aka addons exists on the Server. This is one of the possible ways to do it and should work fine.

Most of the times it would only happen when starting the work in the morning (after Ayons update of server packages) when TDs being sensible about updating of the Ayon pipeline :)

However I do agree that 5 mins interval being quite often would be interesting to test it when hundreds of users connected :)

**Review by LiborBatek — APPROVED** [review]
Works as expected...

Test 01 (Bundle change on the server):

Screenshot 2024-02-08 104156

Test 02 (Server down):

Screenshot 2024-02-08 110007

**Comment by BigRoy** [comment]
> Works as expected...
> 
> Test 01 (Bundle change on the server):
> Screenshot 2024-02-08 104156
> 
> Test 02 (Server down):
> Screenshot 2024-02-08 110007

Is it odd that the second screenshot's dialog doesn't allow you to confirm? :) 

> However I do agree that 5 mins interval being quite often would be interesting to test it when hundreds of users connected 

That too. But to me it's mostly that a user might just be finishing something now - and they don't want to restart all their applications NOW but maybe later today. But now they'd be prompted every five minutes if they click away the dialog to continue. It just feels a bit too frequent, no show-stopper. But definitely frequent.

**Comment by BigRoy** [comment]
Can we close this PR now in favor of https://github.com/ynput/ayon-core/pull/28 or are there still reasons to merge these into OpenPype as well?

**Comment by mkolar** [comment]
> Can we close this PR now in favor of https://github.com/ynput/ayon-core/pull/28 or are there still reasons to merge these into OpenPype as well?

@iLLiCiTiT that's very good question.

**Comment by iLLiCiTiT** [comment]
Yes we can. Closing.

**Pull request closed without merging**
