### PR TITLE
Maya: Template Builder do not put asset in correct hierarchy

### PR DESCRIPTION
**Pull request by friquette**
## Changelog Description
Put assets found by the template builder in the expected hierarchy by parenting the referenced nodes in the parent group of their associated placeholder.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Lol, I literally just done a PR for this :)

https://github.com/ynput/OpenPype/pull/4854

**Comment by friquette** [comment]
> Lol, I literally just done a PR for this :)
> 
> #4854

Yours seems much more complete than mine haha

**Comment by tokejepsen** [comment]
> Yours seems much more complete than mine haha

Should we close this in favour of #4854 ?

**Comment by friquette** [comment]
> > Yours seems much more complete than mine haha
> 
> Should we close this in favour of #4854 ?

I think so yes

**Pull request closed without merging**
