### PR TITLE
Maya: Change namespace for references

### PR DESCRIPTION
**Pull request by friquette**
## Brief description
Change namespace for references in Maya for a better readability. Proposed format: {asset}:{subset}_GRP

### CODE REVIEW

**Comment by tokejepsen** [comment]
This is quite a fundamental change, so it'll need at least a setting that is off by default.

**Comment by moonyuet** [comment]
For this case, it would be great if the users can set their own format for the namespace in the setting instead of hard-coding the format

**Comment by LiborBatek** [comment]
If reviewable pls put some testing notes for user based testing, thx!

**Comment by friquette** [comment]
Hi, I see you closed this PR without merging it. Will it be merged some day or do we need to modify things ?

**Pull request closed without merging**
