### PR TITLE
Houdini: Implement `switch` method on loaders

### LINKED ISSUE #4865: Enhancement: Houdini loaders implement `switch`
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

The houdini loaders currently don't allow to switch asset, this is because they don't have the `switch` method implemented on the loaders.

So basically we need support for the "switch asset" functionality in the Scene Inventory / Manager...

afbeelding

_Screenshot just to highlight what UI feature is related_

### How would you imagine the implementation of the feature?

Since Houdini is heavily procedural I suspect almost all of the loaders can live with a `switch` method implementation that is basically this:

```python
    def switch(self, container, representation):
        self.update(container, representation)
```

Actually a quick code search over the codebase seems that that is exactly the implementation that is basically used on all loaders currently (at least those that support `switch`)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Describe alternatives you've considered:

Removing the container and loading a new is not preferred. :)

### Additional context:

_No response_

[cuID:[OP-5753](https://app.clickup.com/t/861mp6uye)]

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Implement `switch` method on loaders

## Additional info

Fixes #4865 

- Houdini ass loader is skipped: it already had it implemented.
- Houdini hda loader is skipped: I wasn't too sure whether it'd be safe to implement it for the HDA loader.
- _Note that I believe technically the switching allows to switch "loaders" as well instead of only asset, subset or representation and that the `update` method should check for that I believe. However, I haven't seen any implementation as of yet that actually does so._

## Testing notes:

1. Load using the changes loaders.
2. Test switching to another asset (or representation), etc.

### CODE REVIEW

**Comment by moonyuet** [comment]
I have tested the code and it raises the Assertion Error. 
image

**Comment by BigRoy** [comment]
@moonyuet That is interesting. You should be getting the error like [here](https://github.com/ynput/OpenPype/issues/4870#issue-1675008394) if it doesn't have `switch` which it does have now. So we've progressed.

The error you seem to get seems completely unrelated to this PR haha. Does `update` work for you?
I've tried the CameraLoader here now and it seems to work fine for me. Can you try again to be sure and maybe see if you can get more information?

**Comment by moonyuet** [comment]
> @moonyuet That is interesting. You should be getting the error like [here](https://github.com/ynput/OpenPype/issues/4870#issue-1675008394) if it doesn't have `switch` which it does have now. So we've progressed.
> 
> The error you seem to get seems completely unrelated to this PR haha. Does `update` work for you? I've tried the CameraLoader here now and it seems to work fine for me. Can you try again to be sure and maybe see if you can get more information?
> 
> The loader being _incompatible_ should almost definitely be a different issue.

If you talk about the update function of the loaders, they all work in my scene. I actually tested it right before I tested with the switch asset option. 
The video below is I tested with setting up different versions. and it works. 

https://user-images.githubusercontent.com/64118225/233328630-371bd60c-3213-48ee-8549-54b4c4419c67.mp4


I also tested with update to the latest function, it works smoothly.

**Comment by BigRoy** [comment]
> If you talk about the update function of the loaders, they all work in my scene. I actually tested it right before I tested with the switch asset option.
> The video below is I tested with setting up different versions. and it works.

So that means you were able to reproduce the switch asset functionality again? Could you share a recording of how you're doing the asset switching?

**Comment by moonyuet** [comment]
> > If you talk about the update function of the loaders, they all work in my scene. I actually tested it right before I tested with the switch asset option.
> > The video below is I tested with setting up different versions. and it works.
> 
> So that means you were able to reproduce the switch asset functionality again? Could you share a recording of how you're doing the asset switching?

Yes the video below shows the asset switching doesn't work. It could be that Houdini works differently from the hosts like Maya and Max.

https://user-images.githubusercontent.com/64118225/233339292-efa0da7a-0fae-40c2-b398-dcdf7de4387d.mp4

**Comment by BigRoy** [comment]
Isn't it because you're switching to representation that isn't actually supported by that loader and thus you can't switch in a BGEO loader to e.g. loading a `VDB` representation since it's not compatible.
You should be able to "switch" to anything that is still compatible with the BGEO loader itself.

**Comment by moonyuet** [comment]
> Isn't it because you're switching to representation that isn't actually supported by that loader and thus you can't switch in a BGEO loader to e.g. loading a `VDB` representation since it's not compatible. You should be able to "switch" to anything that is still compatible with the BGEO loader itself.
> 
> That's how it behaves in other hosts at least.


> Isn't it because you're switching to representation that isn't actually supported by that loader and thus you can't switch in a BGEO loader to e.g. loading a `VDB` representation since it's not compatible. You should be able to "switch" to anything that is still compatible with the BGEO loader itself.
> 
> That's how it behaves in other hosts at least.



> Isn't it because you're switching to representation that isn't actually supported by that loader and thus you can't switch in a BGEO loader to e.g. loading a `VDB` representation since it's not compatible. You should be able to "switch" to anything that is still compatible with the BGEO loader itself.
> 
> That's how it behaves in other hosts at least.

I see. Maybe I somehow misunderstand how the switch asset works in general. 
After revising the code, all the questions have been resolved.
Most of the current families have separate families.
Even if camera and pointache share the same representation, they are in different loaders.

**Comment by BigRoy** [comment]
Originally switch _**asset**_ was implemented to basically do that, allow switching to loading from a different asset or subset. So they say you could set up your scene for SH010 completely, save your file to SH020 then switch asset all loaded things to SH020 so that now you have used SH010 as a 'template' for SH020 with just the references/loaded content relinked to SH020.

**Comment by moonyuet** [comment]
> Originally switch _**asset**_ was implemented to basically do that, allow switching to loading from a different asset or subset. So they say you could set up your scene for SH010 completely, save your file to SH020 then switch asset all loaded things to SH020 so that now you have used SH010 as a 'template' for SH020 with just the references/loaded content relinked to SH020.

Switch asset works smoothly as thought

https://user-images.githubusercontent.com/64118225/233350911-c4a620d9-a861-4674-b291-297e39be3d9b.mp4

**Review by moonyuet — APPROVED** [review]

**Review by antirotor — APPROVED** [review]

**Pull request merged**
