### PR TITLE
Maya: Fix workfile template placeholder cleanup

### PR DESCRIPTION
**Pull request by SherineKB**
## Changelog Description

**Bug :** If we enable the set suppression, we have an error from the 2nd object because it deletes the set with it.
TypeError: No object matches name: PLACEHOLDERS_SET`
`
To fixe it, we need to firstly remove the object from the set and secondly delete it, so it keeps the set.

**To test it:**
Build workfile
See if the rig assets linked to the shot are loaded (refer to Ftrack).

### CODE REVIEW

**Comment by tokejepsen** [comment]
I cant replicate this error. Using latest `develop` I get this error however;

```
#   - { <openpype.hosts.maya.api.workfile_template_builder.MayaPlaceholderLoadPlugin object at 0x000001BEFC05AFD0> }: [ Placeholder cleanup skipped due to failed placeholder population. ] 
```

Is there something missing in the testing notes?

**Comment by SherineKB** [comment]
> I cant replicate this error. Using latest `develop` I get this error however;
> 
> ```
> #   - { <openpype.hosts.maya.api.workfile_template_builder.MayaPlaceholderLoadPlugin object at 0x000001BEFC05AFD0> }: [ Placeholder cleanup skipped due to failed placeholder population. ] 
> ```
> 
> Is there something missing in the testing notes?

Can you precise the steps to reproduce to get this error please ?

**Comment by tokejepsen** [comment]
Sorry @SherineKB I dont actually seem to get any error atm in latest `develop`. 

Could you maybe give latest `develop` a try and see if the issue still persists?

**Comment by tokejepsen** [comment]
@SherineKB did you get a chance to test latest develop?

**Comment by mkolar** [comment]
@SherineKB we're closing this PR as it is stale and wasn't validated. If you find the error again and would like to contribute the fix, feel free to re-open this again targeting AYON.

**Pull request closed without merging**
