### PR TITLE
Houdini: USD Render actually use Render Products from Render Settings

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

The Collect Render Products logic previously traversed the full USD stage to find all render products, but a Render may not use all Render Products but will only render those defined by the Render Settings - as such, we should be retrieving them from the used Render Settings in the render.

## Additional notes

Came up on Discord [here](https://discord.com/channels/517362899170230292/517382145552154634/1176080300288245840)

More details about USD Rendering:

- [USD Render Schema: Concepts](https://openusd.org/dev/api/usd_render_page_front.html)
- [Houdini USD Render ROP](https://www.sidefx.com/docs/houdini/nodes/out/usdrender.html)

According to [this documentation on `UsdRenderSettingsBase`](https://openusd.org/dev/api/class_usd_render_settings_base.html) it should be possible to also set Render Settings on RenderProduct prims - but how that would work in practice I'm not sure. They state:
> Abstract base class that defines render settings that can be specified on either a RenderSettings prim or a RenderProduct prim.

## Testing notes:

1. Submit USD renders (via _usdrender_ instance!)
2. Render Products should be collected and submitted only for those render products that are in the render settings

Note that the Karma ROP publish instance is **different** from this one since it doesn't use the USD data to collect the expected outputs but instead parses the Karma ROP parms itself. Eventually it'd mean less code duplication if that logic could _also_ adopt reading it from the USD data. But this PR will not touch that.

### CODE REVIEW

**Comment by BigRoy** [comment]
Apparently the USD Render workflow basically didn't work at all to begin with; couldn't even create an instance. So I've fixed that now. I assume that likely there might need to be additional fixes for this to _actually_ work.

@MustafaJafar is this something you'd like to pick up from here? Likely deadline submissions need to be tested, etc.

I have a feeling that `renderProducts` and `colorspaceData` and potentially `expectedFiles` need to get defined as well similar to what Collect Karma ROP does: https://github.com/ynput/OpenPype/blob/8fb7266ff8f0ea9c3b3f387ca120280093993294/openpype/hosts/houdini/plugins/publish/collect_karma_rop.py#L59-L73

**Comment by BigRoy** [comment]
> @BigRoy what is the status of this ticket:)? I have done another simple test in blender. It is published successfully but it seems that the mesh has lost the material during loading. Is it expected or there should be always the same shader? image

@moonyuet as far as I'm aware this PR changes nothing for actual USD file publishing but only for USD rendering from houdini.

As such, the issue you describe should be not be **due** to this PR.

**Comment by BigRoy** [comment]
For what it's worth - we're using a more elaborate state of this currently with a custom Husk Deadline Plug-in and "split export job" support where first the USD file gets written and Husk renders the USD itself.

I'll keep this in draft for the time being until I have something ready to push upstream.

**Comment by mkolar** [comment]
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be re-created to target one of those.

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-core](https://github.com/ynput/ayon-core) or the host addon repository once it's up.

**Pull request closed without merging**
