### PR TITLE
Addons directory

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
This adds a directory for Addons, for easier distribution of studio specific code.

## Additional info
Discussion about how to distribute and maintain studio specific code is going on the forums; https://community.ynput.io/t/studio-specific-code/182/11

## Testing notes:
1. Add an addon to the `openpype/addons` directory.
2. Create a build, zip and installer.
3. Validate the addon files are included with the build, zip and installer.

### CODE REVIEW

**Comment by BigRoy** [comment]
The code changes seem minimal which is nice - but I definitely feel this needs some extra explanation.

- If I for one wanted to distribute my own addons this way, how do I do that? Add your addon into the folder + enable the addon/module or whatever in your system settings?
- Why would I be adding my addon in `addons/` and not in `modules/` - isn't currently the behavior essentially the same?
- What do I set as "addon path" in settings for this path to get picked up? Do I need to set anything?

How are you git versioning your addons? You won't be just putting your git repositories into `/addons` since it would just include the full .git repository into the `.zip` right?

**Comment by BigRoy** [comment]
I can understand your reasoning but I'm not seeing the direct benefit over instead just dropping it into the `modules/` folder if you start putting things inside the OpenPype folder anyway. It's good to see there's some thinking about solutions to this but I'm not sure this PR (in current state) is the best solution to it.

**Comment by BigRoy** [comment]
In our case it's simple, we don't have a separate addon repository. We have our own fork and branch of OpenPype which contains our own "module"/"addon". Having it in `modules/` means we need to set up no addon paths, it's always available as a module like builtin modules but, like builtin modules, can be enabled/disabled.

Yes, it means our code is in the OpenPype folder (and also directly our fork/branch of the OpenPype repository).

**Comment by tokejepsen** [comment]
> Yes, it means our code is in the OpenPype folder (and also directly our fork/branch of the OpenPype repository).

Does that mean your addon is publicly available?

**Comment by BigRoy** [comment]
It is, yes. Here's [our colorbleed module](https://github.com/BigRoy/OpenPype/tree/colorbleed/openpype/modules/colorbleed). However, nothing is stopping you from working with your repository or branch in private I suppose.

**Comment by tokejepsen** [comment]
> It is, yes. Here's [our colorbleed module](https://github.com/BigRoy/OpenPype/tree/colorbleed/openpype/modules/colorbleed). However, nothing is stopping you from working with your repository or branch in private I suppose.

I tend to work in private cause its normally a mess :)

I feel like there would be more management involve in having the addon in `modules`. For example personally I would need to have 2 OpenPype repositories; one private and one public (that is event possible).
Also although you could document how to gitignore your module within the repository, it would need a unique repository per studio.

I'll continue using this `addons` directory for now. Most likely there will be issues that I've not foreseen.

**Comment by iLLiCiTiT** [comment]
> Assuming you can do a relative path to the addons directory, so {OPENPYPE_ROOT}/openpype/addons. But I haven't experimented that far yet.

We should find out if this is possible, or maybe change the behavior in `openpype/modules/base.py` to look into addons too.

> I can understand your reasoning but I'm not seeing the direct benefit over instead just dropping it into the modules/ folder if you start putting things inside the OpenPype folder anyway

One of reasons we changed in AYON that addons are not part of the base is different versioning. So I see the benefit in this approach in having different versions of addon in different versions of openpype, so you can easily change behavior without changes in main repository. And our current approach, using path to addons in System settings, does not allow to use different versions and also the artist must have access to addons directory.

**Review by iLLiCiTiT — APPROVED** [review]
Added addons dir automatically to modules discovery paths. LGTM

**Pull request merged**
