### PR TITLE
Houdini: Add python3.10 libs for Houdini 20 startup

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Add python3.10 libs for Houdini 20 startup

## Additional info

Houdini 20 defaults to Py 3.10

## Testing notes:

1. Launch Houdini 20
2. OpenPype host should install correctly on launch

### CODE REVIEW

**Review by MustafaJafar — APPROVED** [review]
Well, it works. 
image

---

Here's what Houdini's console told me after opening Houdini.

```
Installing OpenPype ...
Setting scene FPS to 25
Updated $RESY to 1080
Updated $RESX to 1920
  - { timers_manager }: [  Installing task changed callback  ] 
Could not initialize the help server:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\houdinihelp\api.py", line 126, in initialize
    bookish_app = get_houdini_app(use_houdini_path=bool(hou))
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\houdinihelp\server.py", line 25, in get_houdini_app
    from bookish import flaskapp, flasksupport
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\bookish\flaskapp.py", line 37, in <module>
    import flask
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\site-packages\flask\__init__.py", line 2, in <module>
    from .app import Flask as Flask
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\site-packages\flask\app.py", line 34, in <module>
    from . import cli
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\site-packages\flask\cli.py", line 15, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (E:\Ynput\OpenPype\.venv\lib\site-packages\click\core.py)

Nothing to change, Houdini vars are already up to date.
= = = Resources registration = = =
ERROR: C:/PROGRA~1/SIDEEF~1/HOUDIN~1.506/packages/apex/viewer_states/apexanimate.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\viewerstate\utils.py", line 967, in register_pystate
    mod = importlib.import_module(module_name)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/packages/apex/viewer_states\apexanimate.py", line 15, in <module>
    from apex.ui.selectionmanager import model as ssm
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/packages/apex/python3.10libs\apex\ui\selectionmanager\model.py", line 9, in <module>
    from poselib.itemlibrary import IdentityProxyModel as plIdentityProxyModel
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\poselib\itemlibrary.py", line 16, in <module>
    from . import plglobals
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\poselib\plglobals.py", line 23, in <module>
    from PIL import Image
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Ynput\OpenPype\.venv\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (E:\Ynput\OpenPype\.venv\lib\site-packages\PIL\__init__.py)

ERROR: C:/PROGRA~1/SIDEEF~1/HOUDIN~1.506/packages/apex/viewer_states/apexposestate.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\viewerstate\utils.py", line 967, in register_pystate
    mod = importlib.import_module(module_name)
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.506\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/packages/apex/viewer_states\apexposestate.py", line 7, in <module>
    import apex.ui.selectionmanager.model as ssm
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/packages/apex/python3.10libs\apex\ui\selectionmanager\model.py", line 9, in <module>
    from poselib.itemlibrary import IdentityProxyModel as plIdentityProxyModel
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\poselib\itemlibrary.py", line 16, in <module>
    from . import plglobals
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.506/houdini/python3.10libs\poselib\plglobals.py", line 23, in <module>
    from PIL import Image
  File "C:\Program Files\Side Effects Software\Houdini 20.0.506\python310\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "E:\Ynput\OpenPype\.venv\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (E:\Ynput\OpenPype\.venv\lib\site-packages\PIL\__init__.py)


>>> [ *** Discovered 1 abstract plugins
- AutoCreator ] 
```

while these errors didn't stop houdini from working, but they did on the farm 
```
﻿=======================================================
Error
=======================================================
FailRenderException : Error: cannot import name 'ParameterSource' from 'click.core' (E:\Ynput\OpenPype\.venv\lib\site-packages\click\core.py)
```

**Comment by BigRoy** [comment]
The click errors are already an issue of its own here: https://github.com/ynput/OpenPype/issues/5921
You should be able to try this PR https://github.com/ynput/OpenPype/pull/5928 maybe @MustafaJafar to see if that avoids those click errors.


Can you confirm whether WITHOUT this PR in Houdini 20 it also works to publish/load, etc? Or is the fix of this PR needed?
Hou 20 is Py3.10 right?

I assume without this PR the startup logs would not show e.g. this: **Installing OpenPype ...**

**Comment by MustafaJafar** [comment]
> Hou 20 is Py3.10 right?

In Houdini 20.0.504 python 3.10.10

>  is the fix of this PR needed?
> I assume without this PR the startup logs would not show e.g. this: Installing OpenPype ...

yes! 
It's not only `Installing OpenPype ...` 
OpenPype or Ayon isn't initialized without this PR. 

> Can you confirm whether WITHOUT this PR in Houdini 20 it also works to publish/load, etc?

I can publish and load without this one https://github.com/ynput/OpenPype/pull/5928


--- 
I merged both this PR and  #5928  
but the error remains, I'll continue my comment in the other PR.

**Comment by BigRoy** [comment]
Thanks for confirming - then at least we'd need this PR for Houdini 20 so thanks for approving this particular one.

**Review by moonyuet — APPROVED** [review]

**Review by antirotor — APPROVED** [review]

**Pull request merged**
