### PR TITLE
Igniter: Update dialog resize won't hide too long versions

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Brief description
Resize of update window is checking size hints before resizing to default sizes.

## Description
Update window had forced size of window which caused that version was not visible if is longer.

### Screenshot
image

## Testing notes:
1. Update window should show full version string

### CODE REVIEW

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
Please, this should be targeted to `release/3.15.x`

**Review by jakubjezek001 — CHANGES_REQUESTED** [review]
I am not able to build it. Not sure if this is happening only at myside. 

```Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype_3.15_up\setup.py", line 10, in <module>
    from cx_Freeze import setup, Executable
  File "C:\CODE\__PYPE\OpenPype_3.15_up\.venv\lib\site-packages\cx_Freeze\__init__.py", line 4, in <module>    from .dist import bdist_rpm, build, build_exe, install, install_exe, setup
  File "C:\CODE\__PYPE\OpenPype_3.15_up\.venv\lib\site-packages\cx_Freeze\dist.py", line 18, in <module>   
    from .windist import bdist_msi
  File "C:\CODE\__PYPE\OpenPype_3.15_up\.venv\lib\site-packages\cx_Freeze\windist.py", line 1, in <module> 
    import distutils.command.bdist_msi
ModuleNotFoundError: No module named 'distutils.command.bdist_msi'```

**Comment by iLLiCiTiT** [comment]
I think you have Python 3.7.x instead of Python 3.9.x ...

**Review by antirotor — APPROVED** [review]
looks ok by me

**Pull request merged**
