### PR TITLE
Loader: Hide inactive versions in UI

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Hide versions with `active` set to `False` in Loader UI.

## Additional info
This required changes in next-minor release too.

## Testing notes:
There is not a function to change or set active of version in our codebase.
1. Open Loader UI
2. Choose a subset with version
3. Find the version in Mongo
4. Set it's `data.active` to `False`
5. Refresh loader UI
6. The version should disappear from UI

### CODE REVIEW

**Comment by jakubjezek001** [comment]
Task linked: [OP-4916 unpublish state filtering on version in UI](https://app.clickup.com/t/6658547/OP-4916)

**Comment by BigRoy** [comment]
Please also test the edge case where for an existing subset you set **all** versions to inactive - which I suppose the loader should then omit completely?

**Comment by iLLiCiTiT** [comment]
> Please also test the edge case where for an existing subset you set all versions to inactive - which I suppose the loader should then omit completely?

Good point. Tested, and the subset is not shown in the UI at all in that case (without crashes).

**Review by kalisp — APPROVED** [review]
I am guessing that the check is only for explicit `active == False`, as I tried to change `data.active` to True, but that didn't bring version back.

**Comment by kalisp** [comment]
Actually what is the reason for this? Wouldn't this have impact on "existence" of the version? 
Shouldn't this affect also `get_version_by_id`, `get_version_by_name`, `version_is_latest` and probably `get_versions` as currently no one is handling if that version is actually active.

**Comment by BigRoy** [comment]
> as I tried to change `data.active` to `True`, but that didn't bring version back.

That should definitely bring it back. If it doesn't I'd consider it a bug.

**Comment by iLLiCiTiT** [comment]
> I am guessing that the check is only for explicit active == False, as I tried to change data.active to True, but that didn't bring version back.

Resolved, a string was used instead of boolean.

> Actually what is the reason for this? Wouldn't this have impact on "existence" of the version?
Shouldn't this affect also get_version_by_id, get_version_by_name, get_versions, get_hero_versions, version_is_latest and probably get_versions as currently no one is handling if that version is actually active.

This is a client request to hide versions in UI, but don't reuse the same version on next published version. That's reason why the default behavior of functions didn't change -> integrateion will consider inactive versions as existing but UI won't show them.

**Pull request merged**
