### PR TITLE
Testing: hou module should be within class code.

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
`hou` module should be within the class code else we'll get pyblish errors from needing to skip the plugin.

## Testing notes:
1. Submit Deadline render from Houdini.
2. Validate the renders are successfull.

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
After running the test, it works as expected from my side.
image

**Comment by tokejepsen** [comment]
> After running the test, it works as expected from my side.

What are all the errors and failed tests?

**Comment by moonyuet** [comment]
> > After running the test, it works as expected from my side.
> 
> What are all the errors and failed tests?



> > After running the test, it works as expected from my side.
> 
> What are all the errors and failed tests?

It's not related to the houdini hosts.They are more likely from Unreal and MongoDB connection.
I can send you the log for references
[test_OP_command_log.txt](https://github.com/ynput/OpenPype/files/13557962/test_OP_command_log.txt)

**Comment by tokejepsen** [comment]
@moonyuet I've updated the testing notes, cause we are not actually testing houdini host yet.

**Pull request merged**
