### PR TITLE
Global, Nuke, Maya - Workfile template builder workflow update

### PR DESCRIPTION
**Pull request by jakubjezek001**
## Brief description
Updating workflow for on demand placeholder removal.

## Description
Presets for workfile template builder are having new attribute for keeping placeholders after they are used. To maintain backward compatibility for deployed studios who are using this workflow we are keeping default as keep and we can remove them in Nuke on demand. 

## Additional info
Global and Maya should work as it was.

## Testing notes [ Nuke ]:
1. Test in `\OP02_VFX_demo` ideally on **sh020**  
2. download [following zip](https://drive.google.com/file/d/1cJCKO8AJzO9Nm7i5-zMMu8D0p2EtDo8Z/view?usp=sharing) and upack it in project structure as follows.
image
3. create preset in your test project settings `project_settings/nuke/templated_workfile_build`
4. In case you  already had some preset then `DO NOT SAVE` and test backward compatibility in Nuke by building from template. All should work as it was. 
5.a If you are creating new preset then paste following onto `project_settings/nuke/templated_workfile_build` and fix the path to your in case it is different.
```
{
    "profiles": [
        {
            "task_types": [
                "Compositing"
            ],
            "task_names": [],
            "path": "{root[work]}/OP02_VFX_demo/templates/comp.nk",
            "placeholder_keep": false
        }
    ]
}
```
5.b [dowload this settings patch](https://drive.google.com/file/d/1zu6AtXZQ8-35C9YDGoymX9JLXGKmIFxa/view?usp=sharing) then copy context of the file to clipboard. Go to `project_settings/nuke/imageio` and RMB click at the ImageIO and __paste__. It will take about 5mins to update and then save the settings.
6. then go to Nuke and 
image
7. template should show in script and no Placeholders should stay in the scene under loaded Read nodes. 
8. Try it again but switch the settings `placeholder_keep` to active.
9. Placeholders should stay in the scene after the template is builded.

### CODE REVIEW

**Comment by 64qam** [comment]
Not sure if I do anything wrong, but the template is always loaded like that:
image

**Comment by LiborBatek** [comment]
Does the same for me...just puts the template graph into sh020 comp as this:

image

**Comment by jakubjezek001** [comment]
I have to update the Testing notes and add 5.b section where the manual update of settings for Nuke ImageIO is described. Also I have found out there was a mistake in the template file so those had been also updated - please re-download the file.

**Comment by jakubjezek001** [comment]
closing this PR because https://github.com/ynput/OpenPype/pull/4266 had been based on the source branch of this PR and developlnet in 4266 is farther.

**Pull request closed without merging**
