### PR TITLE
Maya: import workfile missing - OP-6233

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
Missing `workfile` family to import.

## Testing notes:
1. Publish a workfile.
2. Import the workfile through the Loader.

### CODE REVIEW

**Review by LiborBatek — APPROVED** [review]
All works as expected.

There is now ```Import workfile``` action available in the ```Loader``` and fully functional.

**Comment by iLLiCiTiT** [comment]
I would rather avoid adding `exclude_families` into default filtering options of loader. @antirotor ideas?

**Comment by tokejepsen** [comment]
> I would rather avoid adding `exclude_families` into default filtering options of loader. @antirotor ideas?

An alternative I thought about was to have some sort of exclusion syntax, like `!xgen`.

**Comment by iLLiCiTiT** [comment]
There reversed filtering is breaking https://github.com/ynput/OpenPype/pull/4928 . Also I'm not sure if the action should be visible for all families except `xgen`, it will show for `image`, `render` or custom families that studio defined for their purposes.

**Comment by tokejepsen** [comment]
Up to @m-u-r-p-h-y @iLLiCiTiT @antirotor to decide :)

**Comment by BigRoy** [comment]
> We can do explicit families like in https://github.com/ynput/OpenPype/commit/43ece88f02bf1b35b22d35d3ceeef82241fe2ef3

I'd do that yes, and then discuss other changes like supporting `exclude_families` in a dedicated issue or on the forum. For now it's easiest to match all other plugins and just keep this PR about what it actually intended to solve?

**Comment by mkolar** [comment]
> > We can do explicit families like in [43ece88](https://github.com/ynput/OpenPype/commit/43ece88f02bf1b35b22d35d3ceeef82241fe2ef3)
> 
> I'd do that yes, and then discuss other changes like supporting `exclude_families` in a dedicated issue or on the forum. For now it's easiest to match all other plugins and just keep this PR about what it actually intended to solve?

Agreed 100%

**Pull request merged**
