### PR TITLE
Nuke: fixing UNC support for OCIO path

### PR DESCRIPTION
**Pull request by jakubjezek001**
## Changelog Description
UNC paths were broken on windows for custom OCIO path and this is solving the issue with removed double slash at start of path 

## Testing notes:
1. add UNC path to second anatomy root ("resources") >> on windows just go to folder properties and switch to `share` tab. Then copy past the unc path to the Anatomy windows field. My looks like this 
image
2. add new ocio path to first position on a project `project_settings/global/imageio/ocio_config` and use `{root[resources]}` as part of path >> my looks like this
image

3. save and open Nuke. All should work as expected and the ocio path should be added to the nuke workfile properties looking like this > 
image

4. No warning message about `using previouse ocio config...`

### CODE REVIEW

**Comment by jrsndl** [comment]
This fixes the issue in my tests for new workfiles. For workfiles that have been just versioned up, running the set colorspace helps.

**Review by Minkiu — APPROVED** [review]
Haven't tested, but code look good.

**Comment by 64qam** [comment]
Still have the warning message
image

**Review by 64qam — APPROVED** [review]

**Review by 64qam — APPROVED** [review]

**Comment by jakubjezek001** [comment]
> Still have the warning message image

This message is happening since Nuke is doing the check before any our callbacks are happening. After the script is saved and reopened this popup will not happen.

**Pull request merged**
