### PR TITLE
Resolve: Refactor to New Publisher

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

- [x] Refactor Resolve to use the new publisher instead of old publisher
- [x] Update OpenPype menu to match in style + layout with the menu in Fusion (and order menu entries like other hosts)
- [ ] Refactor Creator logic for CreateShotClip - **CURRENTLY IN DRAFT / NOT FULLY WORKING**
    - [ ] biggest todo I think is the fact that the instances refer to assets (=to be created asset) and tasks (=None) that do not exist.
- [ ] Be able to store Context Data of the new publisher into the Current Project or Timeline* - **TODO**

## Additional info

> **Current Project or Timeline***

Since all publishing logic currently is based on the "Current Timeline" I suppose we might see the 'current timeline' as the Context for Publishing and store the metadata there - which might be nice since there currently doesn't seem to be any means of storing metadata onto the project in Resolve. ([Created a Topic on Blackmagic Design Forum to track that feature request](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=189685))

---

Screenshot:

resolve_new_publisher

## Testing notes:

1. Launch Resolve
2. Should be able to create shot clip instances and publish them (WIP - not functional yet)
    - [x] Creating instances
    - [x] Collecting the instances correctly on reset
    - [ ] Instances should actually be valid for the new publisher (currently doesn't allow the non-existing asset, etc.)
4. Should be able to manage shot clip instances in the publisher
    - [x] Removing instances
    - [x] Updating instances

### CODE REVIEW

**Comment by jakubjezek001** [comment]
I have tried to create clips and it almost worked, just for future reference I am adding traceback here:

```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\ayon-openpype\openpype\pipeline\create\context.py", line 2031, in _create_with_unified_error
    result = creator.create(*args, **kwargs)
  File "C:\CODE\__PYPE\ayon-openpype\openpype\hosts\resolve\plugins\create\create_shot_clip.py", line 268, in create
    track_item.SetClipColor(lib.publish_clip_color)
AttributeError: 'NoneType' object has no attribute 'SetClipColor'```

**Comment by BigRoy** [comment]
So - the current state should be pretty close to what the old stuff did except for the fact that publishing does not work because the `asset` on the instance data refers to an asset that of course does not exist yet - which the new publisher says is **no bueno**. :)

image

With e.g. this data on one of the instances:
image

It basically refers to a non-existing asset `main_sq01sh010` and task `null`.

Not entirely sure where to go from here. Of course there are also still issues that I think `variant` isn't actually defined explicitly per instance it batch creates, that the subset names in the `instance_data` aren't computed the way they should (don't use `get_subset_name` because they already were hardcoded in the `PublishClip` class that creates the clip data, etc.)

I feel this is around the time I'll have to leave it like this and for someone at Ynput to take over the PR for the final stretch @jakubjezek001 @iLLiCiTiT ?

Most of the bigger issues are either "todo" on the top description of this PR or added as `# todo` in the code.

**Comment by BigRoy** [comment]
### Design note

It came up on [discord regarding Hiero create](https://discord.com/channels/517362899170230292/1166670541344747590/1166673984583114813) that it might make more sense to reorder the Keyword attributes so they appear higher:

resolve_and_hiero_createpanel_reorder_attributes

Just cross-posting here to keep track whether it's useful for Resolve refactor here as well.

---

@jakubjezek001 @iLLiCiTiT any news on how to potentially tackle the "asset does not exist" yet issue?

**Comment by iLLiCiTiT** [comment]
I don't know how this works, I think it's using editorial task parent asset.

**Comment by BigRoy** [comment]
> I don't know how this works, I think it's using editorial task parent asset.

Basically, the timeline will get cut up into individual _new_ shots to ingest editorial. At the time of the first publish these assets might not exist yet, the new publisher UI doesn't like that because you then have `CreatedInstance` entries that are set to a non-existing `asset`.

**Comment by iLLiCiTiT** [comment]
I'll quote to a quote
> At the time of the first publish these assets might not exist yet, the new publisher UI doesn't like that because you then have CreatedInstance entries that are set to a non-existing asset.

>  I think it's using editorial task parent asset.

**Comment by jakubjezek001** [comment]
Task linked: [OP-8066 Resolve: update to new publisher](https://app.clickup.com/t/6658547/OP-8066)

**Comment by mkolar** [comment]
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be re-created to target one of those.

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-core](https://github.com/ynput/ayon-core) or the host addon repository once it's up.

**Pull request closed without merging**
