### PR TITLE
3dsmax: Publishing Deadline jobs from RedShift 

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
Fix the bug of being uable to publish deadline jobs from Redshift
Use Current File instead of Published Scene for just Redshift.
1. add save scene before rendering to ensure the scene is saved after the modification.
2. add separated aov files option to allow users to choose to have aovs in render output
3. add validator for render publish to aovid overriding the previous renders
image

## Additional info
**Please delete the old instance and create the new one for the test.**
1. 3dsMax doesn't support OCIO config yet so the related parameter is hardcorded.
2. Max in Redshift does support OCIO and currently hardcoded the data seen from RS in the collector.
5.`rt.Redshift_Renderer().SeparateAovFiles` seems to be broken as it doesn't bind to the render setting when executing the code. So currently please make sure you dont check `Separate AOV Files`. 
image

## Testing notes:
1. Launch 3dsmax via Openpype
6. Use Redshift as Renderer
7. Create Render Instance
8. Publish Render
9. It should only includes MaxRenderMain.exr and Cryptomatte.exr along with metadata in the related output folder

### CODE REVIEW

**Review by m-u-r-p-h-y — CHANGES_REQUESTED** [review]
Publishing is failing with the error:

` openpype.pipeline.publish.publish_plugins.KnownPublishError: Transfer to destination is already in queue:`

@kalisp  is pointing out that we are most probably trying to publish 1 instance with 3 representations (effectively overwriting each other in publish destination) instead of having 3 instances each with 1 representation in Max implementation of `collect_render`

```
2023-05-25 12:17:54:  0: STDOUT: INFO:pyblish.IntegrateAsset:Prepared version: v001
2023-05-25 12:17:54:  0: STDOUT: DEBUG - Anatomy template name: render
2023-05-25 12:17:54:  0: STDOUT: DEBUG:pyblish.IntegrateAsset:Anatomy template name: render
2023-05-25 12:17:54:  0: STDOUT: DEBUG - Template filled: Z://op_dev/shots/shot_0020/publish/render/maxrenderMain/v001/op_dev_shot_0020_maxrenderMain_v001.1001.exr
2023-05-25 12:17:54:  0: STDOUT: DEBUG:pyblish.IntegrateAsset:Template filled: Z://op_dev/shots/shot_0020/publish/render/maxrenderMain/v001/op_dev_shot_0020_maxrenderMain_v001.1001.exr
2023-05-25 12:17:54:  0: STDOUT: DEBUG - Anatomy template name: render
2023-05-25 12:17:54:  0: STDOUT: DEBUG:pyblish.IntegrateAsset:Anatomy template name: render
2023-05-25 12:17:54:  0: STDOUT: DEBUG - Template filled: Z://op_dev/shots/shot_0020/publish/render/maxrenderMain/v001/op_dev_shot_0020_maxrenderMain_v001.1001.exr
2023-05-25 12:17:54:  0: STDOUT: DEBUG:pyblish.IntegrateAsset:Template filled: Z://op_dev/shots/shot_0020/publish/render/maxrenderMain/v001/op_dev_shot_0020_maxrenderMain_v001.1001.exr
2023-05-25 12:17:54:  0: STDOUT: ERROR - Traceback (most recent call last):
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 185, in process
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 318, in register
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\lib\file_transaction.py", line 98, in add
2023-05-25 12:17:54:  0: STDOUT:     raise DuplicateDestinationError(
2023-05-25 12:17:54:  0: STDOUT: openpype.lib.file_transaction.DuplicateDestinationError: Transfer to destination is already in queue: Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain.1001.exr -> Z:\op_dev\shots\shot_0020\publish\render\maxrenderMain\v001\op_dev_shot_0020_maxrenderMain_v001.1001.exr. It's not allowed to be replaced by a new transfer from Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain_RsCustom.1001.exr
2023-05-25 12:17:54:  0: STDOUT: During handling of the above exception, another exception occurred:
2023-05-25 12:17:54:  0: STDOUT: Traceback (most recent call last):
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Program Files (x86)\OpenPype\3.15.1\dependencies\pyblish\plugin.py", line 522, in __explicit_process
2023-05-25 12:17:54:  0: STDOUT:     runner(*args)
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 190, in process
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\qam\code\OpenPype\.venv\lib\site-packages\six.py", line 718, in reraise
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 185, in process
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 318, in register
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\lib\file_transaction.py", line 98, in add
2023-05-25 12:17:54:  0: STDOUT:     raise DuplicateDestinationError(
2023-05-25 12:17:54:  0: STDOUT: openpype.pipeline.publish.publish_plugins.KnownPublishError: Transfer to destination is already in queue: Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain.1001.exr -> Z:\op_dev\shots\shot_0020\publish\render\maxrenderMain\v001\op_dev_shot_0020_maxrenderMain_v001.1001.exr. It's not allowed to be replaced by a new transfer from Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain_RsCustom.1001.exr
2023-05-25 12:17:54:  0: STDOUT: Traceback (most recent call last):
2023-05-25 12:17:54:  0: STDOUT:   File "<string>", line 185, in process
2023-05-25 12:17:54:  0: STDOUT:   File "<string>", line 318, in register
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\lib\file_transaction.py", line 98, in add
2023-05-25 12:17:54:  0: STDOUT:     raise DuplicateDestinationError(
2023-05-25 12:17:54:  0: STDOUT: openpype.lib.file_transaction.DuplicateDestinationError: Transfer to destination is already in queue: Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain.1001.exr -> Z:\op_dev\shots\shot_0020\publish\render\maxrenderMain\v001\op_dev_shot_0020_maxrenderMain_v001.1001.exr. It's not allowed to be replaced by a new transfer from Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain_RsCustom.1001.exr
2023-05-25 12:17:54:  0: STDOUT: During handling of the above exception, another exception occurred:
2023-05-25 12:17:54:  0: STDOUT: Traceback (most recent call last):
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Program Files (x86)\OpenPype\3.15.1\dependencies\pyblish\plugin.py", line 522, in __explicit_process
2023-05-25 12:17:54:  0: STDOUT:     runner(*args)
2023-05-25 12:17:54:  0: STDOUT:   File "<string>", line 190, in process
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\qam\code\OpenPype\.venv\lib\site-packages\six.py", line 718, in reraise
2023-05-25 12:17:54:  0: STDOUT:   File "<string>", line 185, in process
2023-05-25 12:17:54:  0: STDOUT:   File "<string>", line 318, in register
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\lib\file_transaction.py", line 98, in add
2023-05-25 12:17:54:  0: STDOUT:     raise DuplicateDestinationError(
2023-05-25 12:17:54:  0: STDOUT: openpype.pipeline.publish.publish_plugins.KnownPublishError: Transfer to destination is already in queue: Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain.1001.exr -> Z:\op_dev\shots\shot_0020\publish\render\maxrenderMain\v001\op_dev_shot_0020_maxrenderMain_v001.1001.exr. It's not allowed to be replaced by a new transfer from Z:\op_dev\shots\shot_0020\work\Generic\renders\3dsmax\op_dev_shot_0020_Generic_v001\maxrenderMain_RsCustom.1001.exr
2023-05-25 12:17:54:  0: STDOUT: ERROR:pyblish.plugin:Traceback (most recent call last):
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 185, in process
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\plugins\publish\integrate.py", line 318, in register
2023-05-25 12:17:54:  0: STDOUT:   File "C:\Users\Open\AppData\Local\pypeclub\openpype\3.15\openpype-v3.15.7-nightly.2\openpype\lib\file_transaction.py", line 98, in add
2023-05-25 12:17:54:  0: STDOUT:     raise DuplicateDestinationError(
```

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Job successfully submitted to Deadline, all frames get rendered but fails on ```Publish Job```

maybe because several AOVs present inside exr files?!

```
 DEBUG:pyblish.CollectFtrackApi:Instance's context asset is same as in publish context. Asset: teapot
2023-05-26 17:26:45:  0: STDOUT: ERROR - Traceback (most recent call last):
2023-05-26 17:26:45:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-26 17:26:45:  0: STDOUT:     runner(*args)
2023-05-26 17:26:45:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\validate_unique_subsets.py", line 75, in process
2023-05-26 17:26:45:  0: STDOUT: openpype.pipeline.publish.publish_plugins.PublishXmlValidationError: Instance subset names ['teapot > renderLookdevMaxrenderFinal'] are not unique. Please remove or rename duplicates.
2023-05-26 17:26:45:  0: STDOUT: Traceback (most recent call last):
2023-05-26 17:26:45:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-26 17:26:45:  0: STDOUT:     runner(*args)
2023-05-26 17:26:45:  0: STDOUT:   File "<string>", line 75, in process
2023-05-26 17:26:45:  0: STDOUT: openpype.pipeline.publish.publish_plugins.PublishXmlValidationError: Instance subset names ['teapot > renderLookdevMaxrenderFinal'] are not unique. Please remove or rename duplicates.
2023-05-26 17:26:45:  0: STDOUT: ERROR:pyblish.plugin:Traceback (most recent call last):
2023-05-26 17:26:45:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-26 17:26:45:  0: STDOUT:     runner(*args)
2023-05-26 17:26:45:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\validate_unique_subsets.py", line 75, in process
2023-05-26 17:26:45:  0: STDOUT: openpype.pipeline.publish.publish_plugins.PublishXmlValidationError: Instance subset names ['teapot > renderLookdevMaxrenderFinal'] are not unique. Please remove or rename duplicates.
2023-05-26 17:26:45:  0: STDOUT: Traceback (most recent call last):
2023-05-26 17:26:45:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-26 17:26:45:  0: STDOUT:     runner(*args)
2023-05-26 17:26:45:  0: STDOUT:   File "<string>", line 75, in process
2023-05-26 17:26:45:  0: STDOUT: openpype.pipeline.publish.publish_plugins.PublishXmlValidationError: Instance subset names ['teapot > renderLookdevMaxrenderFinal'] are not unique. Please remove or rename duplicates.
2023-05-26 17:26:45:  0: STDOUT: !!! ERR: 2023-05-26 17:26:45,072 >>> { CLI-publish }: [ Failed ValidateSubsetUniqueness: Instance subset names ['teapot > renderLookdevMaxrenderFinal'] are not unique. Please remove or rename duplicates. -- ('D:\\REPO\\OpenPype\\openpype\\plugins\\publish\\validate_unique_subsets.py', 75, 'process', '') ] 
2023-05-26 17:26:45:  0: STDOUT: >>> run disk mapping command ...
2023-05-26 17:26:45:  0: STDOUT: *** disk mapping arguments: ['subst', 'P:', 'D:\\']
2023-05-26 17:26:45:  0: STDOUT: >>> Logging to server is turned ON
2023-05-26 17:26:45:  0: STDOUT: >>> loading environments ...
2023-05-26 17:26:45:  0: STDOUT:   - for Avalon ...
2023-05-26 17:26:45:  0: STDOUT:   - global OpenPype ...
2023-05-26 17:26:45:  0: STDOUT:   - for modules ...
2023-05-26 17:26:45:  0: STDOUT: *** OpenPype [3.15.8] 
2023-05-26 17:26:45:  0: STDOUT: >>> Using OpenPype from [ D:\REPO\OpenPype ]
2023-05-26 17:26:45:  0: STDOUT: ... OpenPype variant:      [ production ]
2023-05-26 17:26:45:  0: STDOUT: ... Running OpenPype from: [ D:\REPO\OpenPype ]
2023-05-26 17:26:45:  0: STDOUT: ... Using mongodb:         [ localhost ]
2023-05-26 17:26:45:  0: STDOUT: ... Using FTrack at:       [ https://pype.ftrackapp.com ]
2023-05-26 17:26:45:  0: STDOUT: ... Logging to MongoDB:    [ localhost ]
2023-05-26 17:26:45:  0: STDOUT: ...   - port:              [ 27017 ]
2023-05-26 17:26:45:  0: STDOUT: ...   - database:          [ openpype ]
2023-05-26 17:26:45:  0: STDOUT: ...   - collection:        [ logs ]
2023-05-26 17:26:45:  0: STDOUT: ...   - user:              [ <N/A> ]
2023-05-26 17:26:45:  0: STDOUT: setting target: deadline
```

Here are the RS settings and render elements present (aka AOVs)
image
File format kept at RS defaults practically:
image

**Comment by moonyuet** [comment]
I have updated the code and changelog.

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Did another go with submit to DL....I have turn few AOVs on and tried to keep defaults of RS (multilayer EXR) and also ```separate files AOVs``` option as a second go for testing but in both cases I get error during publishing:

```
INFO: Using published scene for render D:\Projects\Libor_Tests\assets\props\teapot\publish\workfile\workfileLookdev\v007\220901_teapot_workfileLookdev_v007.max
INFO: Scene name was switched 220901_teapot_lookdev_v006 -> 220901_teapot_workfileLookdev_v007
INFO: Using D:\Projects\Libor_Tests\assets\props\teapot\publish\workfile\workfileLookdev\v007\220901_teapot_workfileLookdev_v007.max for render/export.
DEBUG: Submitting 3dsMax render..
Traceback (most recent call last):
  File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "D:\REPO\OpenPype\openpype\modules\deadline\abstract_submit_deadline.py", line 446, in process
    self.process_submission()
  File "D:\REPO\OpenPype\openpype\modules\deadline\plugins\publish\submit_max_deadline.py", line 181, in process_submission
    payload = self._use_published_name(payload_data)
  File "D:\REPO\OpenPype\openpype\modules\deadline\plugins\publish\submit_max_deadline.py", line 202, in _use_published_name
    raise RuntimeError("No render elements found")
RuntimeError: No render elements found
```

image

**Comment by LiborBatek** [comment]
Here is a default RS settings for output:

image

And alternate (separate AOV files)

image

**Comment by moonyuet** [comment]
> Here is a default RS settings for output:
> 
> image
> 
> And alternate (separate AOV files)
> 
> image

 This one is recommended to be turned off as I find out the exposed parameter does not really link to the render setting. When I tried to set up the parameter with simple functions, it doesn't ask the render setting to check the ` separate aov files` even I refresh the code. Same when I check the  ` separate aov files` and I tried to get parameter from separate aov files, it will always return to False. We perhaps need to submit ticket to Redshift helpdesk to see if they can help with it.  Or, we need to think alternatively, we can add options for enabled aov. If we click the separate aov files in render settings, we need to enable the "enabled aovs" to have the maps.

https://github.com/ynput/OpenPype/assets/64118225/8cc63a22-8e83-4909-a3c1-0ea9abf5e88a

**Comment by LiborBatek** [comment]
I understand that that checkbox ```Separate files for AOVs``` should be ```Off``` but it doesnt work....thats why tried both variants.

The end results are same - getting error message.

If its a max shortcomming, maybe there could be option on OP render isntance so user could decide if ```Multilayer``` or not...

**Review by LiborBatek — DISMISSED** [review]
I was able to successfully publish to Deadline without and with ```Render Elements``` aka ```AOVs``` active.

When rendering without ```AOVs``` the render job finnishes ok and also the publish render job.

Problems comes when rendering with AOVs turned on. (all set to single EXR multilayer file - which is being RS defaults)

the renders are finnished ok to the working folder (v010 in my case)
image

but then when Publish render job is running all frames being moved to publish folder. However it happened to me that it end up in the same Publish folder overwritting the previous rendered frames. It seems that it outputs to the sam publish folder even multiple times (several render jobs get published into the same folder practically in my case v002)

image

Also the ```Publish render Job``` on Deadline starts to fail with following error message:


```
 INFO - Getting root setting for project "Libor_Tests"
2023-05-29 17:01:25:  0: STDOUT: INFO:pyblish.CollectRenderedFiles:Getting root setting for project "Libor_Tests"
2023-05-29 17:01:25:  0: STDOUT: INFO - anatomy: {'work': D:/Projects}
2023-05-29 17:01:25:  0: STDOUT: INFO:pyblish.CollectRenderedFiles:anatomy: {'work': D:/Projects}
2023-05-29 17:01:25:  0: STDOUT: ERROR - Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 149, in process
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 39, in _load_json
2023-05-29 17:01:25:  0: STDOUT: AssertionError: Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: ERROR:pyblish.CollectRenderedFiles:Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 149, in process
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 39, in _load_json
2023-05-29 17:01:25:  0: STDOUT: AssertionError: Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: ERROR - Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\collect_rendered_files.py", line 149, in process
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\collect_rendered_files.py", line 39, in _load_json
2023-05-29 17:01:25:  0: STDOUT: AssertionError: Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: The above exception was the direct cause of the following exception:
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-29 17:01:25:  0: STDOUT:     runner(*args)
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\collect_rendered_files.py", line 168, in process
2023-05-29 17:01:25:  0: STDOUT: Exception: Error
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 149, in process
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 39, in _load_json
2023-05-29 17:01:25:  0: STDOUT: AssertionError: Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: The above exception was the direct cause of the following exception:
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-29 17:01:25:  0: STDOUT:     runner(*args)
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 168, in process
2023-05-29 17:01:25:  0: STDOUT: Exception: Error
2023-05-29 17:01:25:  0: STDOUT: ERROR:pyblish.plugin:Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\collect_rendered_files.py", line 149, in process
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\collect_rendered_files.py", line 39, in _load_json
2023-05-29 17:01:25:  0: STDOUT: AssertionError: Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: The above exception was the direct cause of the following exception:
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-29 17:01:25:  0: STDOUT:     runner(*args)
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\openpype\plugins\publish\collect_rendered_files.py", line 168, in process
2023-05-29 17:01:25:  0: STDOUT: Exception: Error
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 149, in process
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 39, in _load_json
2023-05-29 17:01:25:  0: STDOUT: AssertionError: Path to json file doesn't exist. "D:/Projects/Libor_Tests/assets/props/teapot/work/lookdev/renders/3dsmax/220901_teapot_lookdev_v010/maxrenderMain_metadata.json"
2023-05-29 17:01:25:  0: STDOUT: The above exception was the direct cause of the following exception:
2023-05-29 17:01:25:  0: STDOUT: Traceback (most recent call last):
2023-05-29 17:01:25:  0: STDOUT:   File "D:\REPO\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
2023-05-29 17:01:25:  0: STDOUT:     runner(*args)
2023-05-29 17:01:25:  0: STDOUT:   File "<string>", line 168, in process
2023-05-29 17:01:25:  0: STDOUT: Exception: Error
2023-05-29 17:01:25:  0: STDOUT: !!! ERR: 2023-05-29 17:01:24,947 >>> { CLI-publish }: [ Failed CollectRenderedFiles: Error -- ('D:\\REPO\\OpenPype\\openpype\\plugins\\publish\\collect_rendered_files.py', 168, 'process', '') ] 
2023-05-29 17:01:25:  0: STDOUT: >>> run disk mapping command ...
2023-05-29 17:01:25:  0: STDOUT: *** disk mapping arguments: ['subst', 'P:', 'D:\\']
2023-05-29 17:01:25:  0: STDOUT: >>> Logging to server is turned ON
2023-05-29 17:01:25:  0: STDOUT: >>> loading environments ...
2023-05-29 17:01:25:  0: STDOUT:   - for Avalon ...
2023-05-29 17:01:25:  0: STDOUT:   - global OpenPype ...
2023-05-29 17:01:25:  0: STDOUT:   - for modules ...
2023-05-29 17:01:25:  0: STDOUT: *** OpenPype [3.15.9-nightly.1] 
2023-05-29 17:01:25:  0: STDOUT: >>> Using OpenPype from [ D:\REPO\OpenPype ]
2023-05-29 17:01:25:  0: STDOUT: ... OpenPype variant:      [ production ]
2023-05-29 17:01:25:  0: STDOUT: ... Running OpenPype from: [ D:\REPO\OpenPype ]
2023-05-29 17:01:25:  0: STDOUT: ... Using mongodb:         [ localhost ]
2023-05-29 17:01:25:  0: STDOUT: ... Using FTrack at:       [ https://pype.ftrackapp.com ]
2023-05-29 17:01:25:  0: STDOUT: ... Logging to MongoDB:    [ localhost ]
2023-05-29 17:01:25:  0: STDOUT: ...   - port:              [ 27017 ]
2023-05-29 17:01:25:  0: STDOUT: ...   - database:          [ openpype ]
2023-05-29 17:01:25:  0: STDOUT: ...   - collection:        [ logs ]
2023-05-29 17:01:25:  0: STDOUT: ...   - user:              [ <N/A> ]
2023-05-29 17:01:25:  0: STDOUT: setting target: deadline
2023-05-29 17:01:25:  0: STDOUT: setting target: farm
2023-05-29 17:01:25:  0: STDOUT: Using plugins:
```

**Review by antirotor — APPROVED** [review]
There are still things that we'll need to handle and unite with other hosts, but lets use this as a base for future work :)

**Review by m-u-r-p-h-y — APPROVED** [review]
basic publishing works now! 

image

**Review by m-u-r-p-h-y — APPROVED** [review]
basic publishing works now! 

image

**Pull request merged**
