### PR TITLE
Gaffer Integration

### PR DESCRIPTION
**Pull request by BigRoy**
## Brief description

OpenPype integration for [Gaffer](https://www.gafferhq.org/)

## Description

This is a prototype/draft integration for OpenPype with Gaffer. The Qt tools load and a few Loaders are implemented as an example, including support for managing versions after they were loaded.

Status:
- [x] Implement Host
- [x] Implement Qt tools
- [x] Implement loaders 
- [ ] Implement save/load/new scene callbacks
    - [x] New scene callback sets `projectRootDirectory` variable - thanks @sjt-rvx
- [x] Implement publishing logic 

## Additional info

~I've tested on Windows using the latest pre-release that has an official windows build. [You can get the Gaffer 1.2.0.0a1 pre-release here](https://github.com/GafferHQ/gaffer/releases/tag/1.2.0.0a1).~ This has now been tested using Gaffer 1.3.8.0.
To run, check out this branch, download Gaffer and unzip the install to e.g. `C:/` and settings will pick it up.
For other locations or Linux you'll likely need to tweak System settings to define where you've installed Gaffer.

[Discussion on Gaffer google groups about OpenPype - Gaffer integration](https://groups.google.com/u/1/g/gaffer-dev/c/S9OqGY120-g)

#### Only one main Gaffer window is supported

Gaffer is able to have multiple windows of Gaffer running in a single session with a single Python environment. As far as I know there's currently no way to have multiple "OpenPype sessions" in Python for the UIs, publishing and 'global' context. As such for now I've worked around this by forcing a singular 'global root' to be set at any point in time, see `set_root` and `get_root` functions in the implementation.

### Gaffer references

- [Gaffer Resources](https://www.gafferhq.org/resources/)
- [Gaffer Deadline](https://github.com/ericmehl/GafferDeadline)
- [Shotgrid tk-gaffer](https://github.com/diegogarciahuerta/tk-gaffer)

## Testing notes:

1. Download latest Gaffer
2. Run Gaffer through launcher
3. Use OpenPype tools through top menu

### CODE REVIEW

**Comment by BigRoy** [comment]
Some visual previews.

Top OpenPype menu:
afbeelding

Loading pointcache:
afbeelding

And managing using manager / scene inventory:
afbeelding

Saving and loading workfiles:
afbeelding


And of course in the launcher:
afbeelding

**Comment by BigRoy** [comment]
Oops - that didn't do what it should do. 🔥 🧯

**Comment by boberfly** [comment]
Hey @BigRoy 

I did a local rebase of this on the latest develop nightly and with Gaffer 1.2.4.0 on windows - I'm not too familiar with OpenPype yet but does it enforce a Python version onto the DCC app? I am having a conflict trying to load from gaffer.cmd and my first guess could be the Python 3.7 vs 3.9 differences, or conflict of what OpenPype provides into pathing vs Gaffer:

```
ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\GafferImage\defaultColorSpace.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\GafferImage\defaultColorSpace.py", line 1, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\editor.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\editor.py", line 39, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\graphEditor.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\graphEditor.py", line 46, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\lightEditor.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\lightEditor.py", line 41, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\menus.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\menus.py", line 49, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\nodeEditor.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\nodeEditor.py", line 38, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\ocio.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\ocio.py", line 44, in <module>
    import PyOpenColorIO as OCIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\shaderView.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\shaderView.py", line 41, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

ERROR : IECore.loadConfig : Error executing file "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\viewer.py" - "DLL load failed: The specified module could not be found.".
 Traceback (most recent call last):
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\IECore\ConfigLoader.py", line 79, in loadConfig
    fileContextDict, fileContextDict
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\startup\gui\viewer.py", line 48, in <module>
    import GafferSceneUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferSceneUI\__init__.py", line 38, in <module>
    __import__( "GafferImageUI" )
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\__init__.py", line 83, in <module>
    from . import DisplayTransformUI
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\GafferImageUI\DisplayTransformUI.py", line 37, in <module>
    import PyOpenColorIO
  File "C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

C:\opt\gaffer\gaffer-1.2.4.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py:142: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return original_import(name, *args, **kwargs)
C:\Program Files (x86)\OpenPype\3.15.6\dependencies\pyblish\vendor\iscompatible.py:44: DeprecationWarning: invalid escape sequence \
  """
C:\Program Files (x86)\OpenPype\3.15.6\dependencies\pyblish\plugin.py:150: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args_ = inspect.getargspec(plugin.process).args
C:\Program Files (x86)\OpenPype\3.15.6\dependencies\pyblish\plugin.py:318: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  for arg in ("instance", "context")):
Installing OpenPype ...
*** WRN: >>> { SyncServer-SFTPHandler }: [  Import FAILED, imported from Python 2, operations will fail.  ]
ERROR : GafferUI.Layouts : Failed to load "Standard" layout. GafferSceneUI is not available.
```

**Comment by boberfly** [comment]
I moved `PyOpenColorIO.pyd` out of `dependencies` and that seemed to fix things. Should that module be moved to `vendor/python` ?

**Comment by alexandre-james** [comment]
> I moved `PyOpenColorIO.pyd` out of `dependencies` and that seemed to fix things. Should that module be moved to `vendor/python` ?

Hi @boberfly !
I had the same errors. But after having moving out 'PyOpenColorIO.pyd' some warnings remains at the end.

```
C:\opt\gaffer-1.2.0.0-windows\python\shiboken2\files.dir\shibokensupport\feature.py:143: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return original_import(name, *args, **kwargs)
C:\opt\OpenPype\.venv\lib\site-packages\pymongo\mongo_client.py:705: DeprecationWarning: Option 'ssl_ca_certs' is deprecated, use 'tlsCAFile' instead.
  keyword_opts = _handle_option_deprecations(keyword_opts)
C:\opt\OpenPype\.venv\lib\site-packages\pyblish\plugin.py:150: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  args_ = inspect.getargspec(plugin.process).args
C:\opt\OpenPype\.venv\lib\site-packages\pyblish\plugin.py:318: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  for arg in ("instance", "context")):
Installing OpenPype ...
```

And it crashed few seconds after.
Have you made other fixes that could have changed the behavior of the program?

**Comment by BigRoy** [comment]
Great to see activity here and thanks for testing. Admittedly some of these things are out of my scope too but reckon some of these might be due to more recent Python version changes in Gaffer itself or alike (or something I've just missed?). Last test runs I had done worked fine for me at the time.

Anyway, @iLLiCiTiT any chance you have some pointers for @alexandre-james 's [questions here](https://github.com/ynput/OpenPype/pull/4267#issuecomment-1571776500). Some seem related to pymongo, pyblish-base and shiboken code giving deprecation warnings.

---

For sake of testing @alexandre-james I've now updated the branch to develop. I'm not sure how old my PR was with regards to the OpenPype version but you might need to recreate the poetry environment with the right python version to ensure it's still valid with OpenPype. It could be that this update might've already fixed some of the issues you're facing.

**Comment by alexandre-james** [comment]
Thank you so much @BigRoy @iLLiCiTiT for your advice,
I have pulled but these warnings persists.

After trying to manually fix the deprecated code, I have made the Pymongo and Pyblish warning disappear.
However, the Shiboken one is still there, and this is just mind blowing, this error makes no sense.

```
C:\opt\gaffer-1.2.0.0a1-windows\python\shiboken2\files.dir\shibokensupport\feature.py:142: DeprecationWarning: Using or importing the ABCs from 'collections.abc' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return original_import(name, *args, **kwargs)
Installing OpenPype ...
```
I will try to look forward to other environments, but I can't deal without Python 3.9 as OpenPype doesn't accept other versions.

`>>> Detecting host Python ... FAILED Version [3.8]is old and unsupported`

**Comment by BigRoy** [comment]
> >>> Detecting host Python ... FAILED Version [3.8]is old and unsupported

This is during building the poetry environment, right? If so, I tend to do something like this to ensure it picks up exactly the python I want it to pick.
```bat
set PATH=%LOCALAPPDATA%\Programs\Python\Python39;%PATH%
set PATH=C:\Program Files\Git\bin;%PATH%
cd /d E:\openpype\OpenPype
.\tools\create_env.ps1
.\tools\fetch_thirdparty_libs.ps1
```
It seems you might have Python 3.8 on your `PATH` env var by default?

**Comment by boberfly** [comment]
Hi @alexandre-james 

I rebased this branch on the latest + my opencolorio fix and it seemed to run reliably for me - does Gaffer run reliably without OpenPype for you normally? I do get those warnings but I've mostly ignored it as Gaffer is using Python 3.7 still and I expect those to go away in future upgrades or custom Gaffer builds with Python 3.9+.

**Comment by alexandre-james** [comment]
> It seems you might have Python 3.8 on your `PATH` env var by default? Not sure if that causes any other issues but I'd try and avoid having it directly on PATH too.

Yes it was on the poetry building, python was on the Env:Path variable so thank you I will do that now

**Comment by alexandre-james** [comment]
> Hi @alexandre-james
> 
> I rebased this branch on the latest + my opencolorio fix and it seemed to run reliably for me - does Gaffer run reliably without OpenPype for you normally? I do get those warnings but I've mostly ignored it as Gaffer is using Python 3.7 still and I expect those to go away in future upgrades or custom Gaffer builds with Python 3.9+.

Thank you @boberfly, if it works for you, the error seems to come from elsewhere. When my terminal crashes there is no mean to see the error report. Thus, I was wondering how did you do to see these two lines ?

```
*** WRN: >>> { SyncServer-SFTPHandler }: [  Import FAILED, imported from Python 2, operations will fail.  ]
ERROR : GafferUI.Layouts : Failed to load "Standard" layout. GafferSceneUI is not available.
```

Also, my Gaffer is running fine without OpenPype.

**Comment by iLLiCiTiT** [comment]
> *** WRN: >>> { SyncServer-SFTPHandler }: [  Import FAILED, imported from Python 2, operations will fail.  ]
  - { timers_manager }: [  Installing task changed callback  ]
  
You can ignore this.

> ERROR : GafferUI.Layouts : Failed to load "Standard" layout. GafferSceneUI is not available.

This could be the source of the bug with menu. Maybe gaffer changed some UI classes?

**Comment by BigRoy** [comment]
So I've just updated this PR to match with OpenPype latest develop branch, made the Gaffer SceneReader also load USD publishes and did some very minor tweaks - I was surprised to see that `gaffer-1.3.7.0-windows` just opens fine.

It'd be great if others could test the PR and mention what's lacking for their needs.

**Comment by BigRoy** [comment]
Since there was a bit more testing being done for this PR by [someone on discord](https://discord.com/channels/517362899170230292/1181872253546283069) I took another look and implemented some things:

- It will now publish workfiles
- You can now publish and reference a "box" for re-use. (like a compound with promoted attributes, etc.)
- It now supports OpenPype's open last workfile on launch
- Context data for the publisher now persists

Especially the publishing prototype here could be a good start for more testing and also for other publish types to be implemented, like renders, etc.

**Comment by BigRoy** [comment]
@alexandre-james if you're still interested - any chance you'd like to test with the updated current state?
@boberfly thanks again for the test run; I've done recent test runs and it works fine out of the box now. Any testing and feature/change requests are more than welcome! :) I haven't used Gaffer much and we're not using it in production so I'd be merely going off of community requests or hoping someone to take over this PR's development if they are looking to use it in production.

**Comment by BigRoy** [comment]
Some **requests** came up on Discord [here](https://discord.com/channels/517362899170230292/1181872253546283069/1182266356343771236).

reference

> 1. when loading the asset, its called "Reference"... it would have been ideal to have the same name as the asset

Yup, doable!

> 2. Also have the option to import. Since Gaffer is the last step in a 3D production pipeline. It would be better if we have the possibility to edit imported nodes. In our case: we intend to tweak lighting of shots. This means lights & shader that are loaded as assets must be editable. The possibility to edit what is up the chain is quite cruicial 

A separate import function should be doable as well. These would then be unmanaged by OpenPype/AYON (unable to version up/down)?

**Comment by BigRoy** [comment]
I believe @sjt-rvx is testing (and developing!?) this with AYON currently.
@mkolar what would be needed to make this get an official AYON compatible stamp.

I believe @sjt-rvx even at one point had a AYON standalone addon for this - however since I was helping out for a bit and wasn't running AYON yet he's halted that for a bit and continued testing with AYON with the application within the OpenPype package.

Since there's now slightly more interest it seems I guess it's a fine time to see what's needed to get this off the ground before it ends up in limbo? :) (Even though it is quite a big feature after wanting to "stop" supporting OpenPype in some time I believe the end goal here is including this with AYON as a target.)

**Comment by mkolar** [comment]
We're happy to prep **ayon-gaffer** and lend and ownership of it if you folks are interested in pushing this. Splitting the repos gives us the freedom to let more people drive individual addons without the need for tight oversight from our end. @sjt-rvx would you be interested in giving it a shot. We'd be able to potentially release is even as alpha or beta stage to AYON market, for more traction.

**Pull request closed without merging**
