### PR TITLE
Maya: Remove duplicated attributes of MTOA verbosity level 

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
Remove duplicated attributes implementation mentioned in https://github.com/ynput/OpenPype/pull/5931#discussion_r1402175289

## Additional info
n/a

## Testing notes:
1.Go to Openpype Settings -> project_settings/deadline/publish/MayaSubmitDeadline/pluginInfo

2. Add {"ArnoldVerbose": 2}

3. Launch Maya via launcher with your rendering scene

4. Make sure your current renderer is Arnold

5. Publish

### CODE REVIEW

**Comment by BigRoy** [comment]
Actually looking at this code - when is `_get_arnold_render_payload` ever called? Is it unused?

**Comment by moonyuet** [comment]
> Actually looking at this code - when is `_get_arnold_render_payload` ever called? Is it unused?

 I dont think I am the best person to answer this. Maybe @antirotor has an idea of where the payload function is being used.

**Comment by antirotor** [comment]
> I'm pretty sure it's unused.

Yes,  unused. It is remnant of support for direct rendering of ass files if I remember correctly and can be removed, but not in this PR.

**Comment by moonyuet** [comment]
@LiborBatek can you test to see if there is any small error after the removal so that i can merge this?

**Review by LiborBatek — APPROVED** [review]
This PR correctly uses the forced params during DL job as seen below

In maya ```verbosity level 0``` 

image

while when on DL it uses the forced ```verbosity 3``` level as set via custom param in OP Setting
DL_Verbosity3
s:

**Pull request merged**
