### PR TITLE
3dsMax: Use relative path to MAX_HOST_DIR

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Use `MAX_HOST_DIR` to calculate startup script path instead of use relative path to `OPENPYPE_ROOT` environment variable.

## Additional info
This should fix startup logic of 3dsMax in AYON.

## Testing notes:
1. Launch 3dsMax via launcher
2. Integration should be available

### CODE REVIEW

**Review by moonyuet — CHANGES_REQUESTED** [review]
image
It works fine in Openpype but it doesn't show up in AYON.
Maybe  the environment of 3dsmax set in studio settings is related to this issue.
image

**Comment by iLLiCiTiT** [comment]
> It works fine in Openpype but it doesn't show up in AYON.

You're looking to wrong project. Applications are set by project and you're looking at `test_project` but in web UI is project ending with `...1234`.

**Comment by moonyuet** [comment]
> > It works fine in Openpype but it doesn't show up in AYON.
> 
> You're looking to wrong project. Applications are set by project and you're looking at `test_project` but in web UI is project ending with `...1234`.

1234 is the code of the project. 
The name of the project is `test_project`
image

**Comment by iLLiCiTiT** [comment]
Ok, that's unrelated to this PR and will write you in PM. If it works in OpenPype it will work in AYON.

**Review by moonyuet — APPROVED** [review]

**Pull request merged**
