### PR TITLE
Enhancement/houdini rearrange ayon houdini settings files

### PR DESCRIPTION
**Pull request by MustafaJafar**
## Changelog Description
Rearranging Houdini Settings to be more readable, easier to edit, update settings (include all families/product types)
This PR is mainly for Ayon Settings to have more organized files. 
For Openpype, I'll make sure that  each Houdini setting in Ayon has an equivalent in Openpype. 

- [x] update Ayon settings, fix typos and remove deprecated settings. 
- [x] Sync with Openpype
- [x] Test in Openpype
- [x] Test in Ayon

## Testing notes:
Every thing should be working the same in Openpype and Ayon

### CODE REVIEW

**Review by moonyuet — APPROVED** [review]
I have tested in my side, all settings are all correct and it doesn't break the setting page for houdini hosts. 
image
I also tried this in Ayon. I can publish cache and render.

**Comment by MustafaJafar** [comment]
> I dont think the code would affect Openpype settings as it doesn't touch any schema settings which is hooked to Openpype.

I didn't touch schema settings yet, I will update them to show the same settings in Ayon.

**Comment by MustafaJafar** [comment]
Shelves manager now in Ayon works the same as Openpype.

**Comment by BigRoy** [comment]
Will have to leave this review to someone else.

**Comment by moonyuet** [comment]
@MustafaJafar is it ready for review?

**Comment by MustafaJafar** [comment]
> @MustafaJafar is it ready for review?

Not yet, I'm just waiting this almost to merge PR https://github.com/ynput/OpenPype/pull/5698 to fix the resultant conflict.

**Comment by MustafaJafar** [comment]
I bumped the minor version as I made some changes in the files structure.

**Review by moonyuet — APPROVED** [review]
Also tested with OP Settings looks good.
image

**Pull request merged**
