### PR TITLE
ExtractOIIOTranscode: Missing product_names to subsets conversion.

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
The `Product Names` filtering should be fixed with this.

## Testing notes:
1. Setup `ayon+settings://core/publish/ExtractReview/profiles/0/outputs?project=demo_Commercial` as below;
Capture
2. Submit render from Maya to Deadline.
3. Inspect Deadline jobs logs that the `ExtractOIIOTranscode` is working on the render.

### CODE REVIEW

**Review by jakubjezek001 — APPROVED** [review]
lgtm

**Comment by LiborBatek** [comment]
Note: Im testing it right now (before get merged) will update here soon...

**Comment by tokejepsen** [comment]
> All works as expected! No errors given and job successfully finnished on DL and product integrated on Ayon server...

Could you post the Deadline job report?

**Comment by LiborBatek** [comment]
Yeah, here you have the Publish Job (DL) report:

[Job_2024-01-25_16-55-31_65b284734e1c57cf378118c5.txt](https://github.com/ynput/OpenPype/files/14054612/Job_2024-01-25_16-55-31_65b284734e1c57cf378118c5.txt)

**Comment by tokejepsen** [comment]
> Yeah, here you have the Publish Job (DL) report:

Cool, it actually ended up skipping the OIIO transcode due to the regex `.*[mM]ain\b` excludes `renderLookdevMain_beauty`, but it still proves the code is working.

We really need some documentation on the whole OIIO transcode for renders from Maya. Especially when dealing with render pases.

**Pull request merged**
