### PR TITLE
Max: Implementation of the validator for model name 

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
Implement the validator for model name in 3dsmax

## Additional info
The validation regex by default is `(.*)_(?P<subset>.*)_(GEO)` and 
your model name should be {Some name}_{SubsetName}_GEO
## Testing notes: 
1. Go to OP/AYON Settings
2. Turn on Validate Model Name
3. Set your preferred validation regex for checking your model name
4. Validate Model Name would check your name accordingly with your validation regex

### CODE REVIEW

**Comment by LiborBatek** [comment]
When inspecting the Validator Settings in Ayon,

is that regex correct? I mean this is how it looks when defaults (obviously not matching the one mentioned above):

image

**Comment by moonyuet** [comment]
> When inspecting the Validator Settings in Ayon,
> 
> is that regex correct? I mean this is how it looks when defaults (obviously not matching the one mentioned above):
> 
> image

No, it should be `(.*)_(?P<subset>.*)_(GEO)`, I will update it back

**Review by LiborBatek — COMMENTED** [review]
The ```Validator``` for Naming works as expected and follows the ```regex``` set in Ayon Settings for max addon.

I have set mine to:

Screenshot 2024-02-05 132240

Validator kicked in when my geometry had different naming:

Screenshot 2024-02-05 132008

So this worked fine. Small note tho: the ```Select Invalid``` didnt do anything.
After adjusting my geometry naming following the one set in Validator all Published OK and without any issues.
Screenshot 2024-02-05 132132

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Now the regex being correctly prefilled in the addon settings.

Validator works correctly, but the ```Select Invalid``` does not  work ATM giving error:

```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2401161802_windows.zip\dependencies\pyblish\plugin.py", line 527, in __explicit_process
    runner(*args)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.18.7-nightly.1\openpype\hosts\max\api\action.py", line 34, in process
    invalid_names = [obj.name for obj in invalid]
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\openpype_3.18.7-nightly.1\openpype\hosts\max\api\action.py", line 34, in <listcomp>
    invalid_names = [obj.name for obj in invalid]
AttributeError: 'tuple' object has no attribute 'name'
```

**Comment by dee-ynput** [comment]
closing: won't do - done in AYON (https://github.com/ynput/ayon-core/pull/59)

**Pull request closed without merging**
