### PR TITLE
Bugfix in houdini shelves manager and beautify settings 

### PR DESCRIPTION
**Pull request by MustafaJafar**
## Changelog Description
This PR fixes the problem in this PR https://github.com/ynput/OpenPype/issues/5457 by using the right function to load a pre-made houdini `.shelf` file 

Also, it beautifies houdini shelves settings to provide better guidance for users which helps with other issue https://github.com/ynput/OpenPype/issues/5458 , Rather adding default shelf and set names, I'll educate users how to use the tool correctly.

Users now are able to select between the two options.

| OpenPype | Ayon |
| -- | -- |
| image | image | 

## Testing notes:
1. Add shelves, everything should be the same.

### CODE REVIEW

**Review by BigRoy — APPROVED** [review]
Didn't test it (we don't use the feature) but screenshots plus code changes look good.

**Comment by iLLiCiTiT** [comment]
Quick question: Is the logic that only one or none of the two options should be filled?

**Comment by MustafaJafar** [comment]
> Quick question: Is the logic that only one or none of the two options should be filled?

Settings themselves are empty by default 
image

As soon as a user hits ( `+` )  button, It's either option 1 or option 2 
Ayon will not complain about any empty fields and Houdini will do nothing if they are empty 

image

**Comment by iLLiCiTiT** [comment]
So I can fill both Option 1 and Option 2?

**Comment by BigRoy** [comment]
> So I can fill both Option 1 and Option 2?

You can fill in Option 1 **OR** Option 2 - one of the two. If both are filled in, Option 1 is only used.

**Comment by iLLiCiTiT** [comment]
So we should use `"dict-conditional"` type in OpenPype and "conditionalEnum" in AYON https://github.com/ynput/ayon-example-addon/blob/main/settings.py#L86 . With that user select in enum which option he would like to use, and only inputs for the selected one are showed in UI...

**Comment by MustafaJafar** [comment]
> So we should use "dict-conditional" type in OpenPype and ["conditionalEnum"](https://github.com/ynput/ayon-example-addon/blob/main/settings.py#L86) in AYON. With that user select in enum which option he would like to use, and only inputs for the selected one are showed in UI...

This is pretty interesting!

**Comment by moonyuet** [comment]
I tried with OP/AYON, all seem working fine
image
image

**Review by mkolar — APPROVED** [review]

**Pull request merged**
