### PR TITLE
Git: add pre-commit hooks

### PR DESCRIPTION
**Pull request by antirotor**
## Description

This PR is adding [pre-commit](https://pre-commit.com/) to OpenPype. It comes with pre-configured checks:

#### trailing-whitespace
check for trailing whitespace

#### end-of-file-fixer
check if there is no new line at the end of the file

#### check-yaml
check yaml syntax

#### check-added-large-files
check if newly added files are larger than 500 Kb (default value)

#### no-commit-to-branch
check that the commit  goes to sane branch defined with following regex:
```
^(?!((enhancement|feature|bugfix|documentation|tests|local)\/[a-zA-Z0-9\-]+)$).*
```
so that will prevent accidental commits to main, develop and various custom branch names. Only allowed branch prefixes are:
enhancement, feature, bugfix, documentation, tests, local

and lastly it is running the code against [black](https://github.com/psf/black).

More can be added to `.pre-commit-config.yaml`

## Installation

You can either run `create_env` script, or manually run `./.poetry/bin/poetry run pre-commit install`.

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
The PR is mixing 3.15.* changes and develop changes.

**Comment by antirotor** [comment]
> The PR is mixing 3.15.* changes and develop changes.

what changes? If you refer to the fixes on `create_env`, they are needed even in 3.14

**Comment by iLLiCiTiT** [comment]
Poetry

**Comment by antirotor** [comment]
> `Poetry.lock` file

that is just result of running `poetry update` against current **pyproject.toml** so I guess it isn't adding anything new or changing major versions. And if it does, it is a matter of tighter version specifications.

**Comment by iLLiCiTiT** [comment]
The issue is that poetry.lock is already changed in release 3.15.x branch and it would be hell to resolve it with all these changes.

**Comment by kalisp** [comment]
Didn't we also had "chore" branches? (These were for refactoring cases, eg. it is not a new feature, nor bugfix.)
(That's for the limiting regex.)

**Review by jakubjezek001 — APPROVED** [review]

**Pull request merged**
