### PR TITLE
Maya: Simplify pointcache proxy integration

### PR DESCRIPTION
**Pull request by tokejepsen**
## Brief description
Missing commit for #4449 

This makes pointcache proxy and Arnold Scene Source proxy use the same integration workflow.

## Testing notes
1. Create pointcache in Maya and add meshes to the proxy objectset.
2. Publish.
3. Check the proxy alembic is integrated rather than ending up in the `resources` folder.

### CODE REVIEW

**Comment by LiborBatek** [comment]
Please provide some testing steps...thx

**Comment by tokejepsen** [comment]
> Please provide some testing steps...thx

Sorry, my bad! Done now.

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Following testing steps it gives me this error during Publish:
4461_publishWithProxyGeo

when no proxy meshes added the pointcache publishes normally and can be loaded via asset loader...
4461_publishWithoutProxyGeo

I did try to add the asset geometries to the ```proxy_SET``` but gave me also that errors. So it do not work when any geometry added to the set.

**Comment by tokejepsen** [comment]
@LiborBatek thanks for testing. Should be fixed now.

**Comment by moonyuet** [comment]
The code looks okay to me. The only thing I suugested would be adding some info to inform the users about the proxy extraction(personal preference only)
```
        if not instance.data.get("proxy"):
            return

        self.log.info("Extracting proxy pointcache..")
```

**Review by moonyuet — APPROVED** [review]

**Comment by LiborBatek** [comment]
Now it works when added some geometry to the ```proxy_SET```.

image

Also outputted the ```pointcache``` and ```pointcache_Proxy``` ok.

**Comment by tokejepsen** [comment]
@mkolar ready to merge.

**Pull request merged**
