### PR TITLE
Testing: Release Maya/Deadline job from pending when testing.

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
When testing we wont put the Deadline jobs into pending with dependencies, so the worker can start as soon as possible.

## Testing notes:
```
openpype_console runtests C:\Users\tokejepsen\OpenPype\tests\integration\hosts\maya\test_deadline_publish_in_maya.py --mongo_url "mongodb://localhost:2707/"
```
Verify the jobs on Deadline are not put into pending initially.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Split from #5644

**Review by kalisp — CHANGES_REQUESTED** [review]
Are the changes in `submit*` absolute necessary? They are ugly af.

I don't see to much performance gains vs polluting code with this check. (I cry anytime I need to put one of these somewhere.)

**Comment by tokejepsen** [comment]
@kalisp not sure what removing the render instance, has to do with this PR?
It has introduced a merge conflict as well.

> Are the changes in submit* absolute necessary? They are ugly af.

I would be up for leaving the changes in submit plugin, as it could introduce issues down the line if spawning multiple workers on a machine.

**Review by kalisp — APPROVED** [review]

**Comment by kalisp** [comment]
It seems to work and doesn't break anything else.

**Pull request merged**
