### PR TITLE
Bugfix: Houdini license validator missing families

### PR DESCRIPTION
**Pull request by MustafaJafar**
## Changelog Description
Adding missing families to Houdini license validator.

image

image

## Testing notes:
Try exporting these product types from Houdini Apprentice, License Validator should tell as the following screenshot. 
 1. usd
 2. point cache abc
 3. static mesh fbx
 4. camera

image

### CODE REVIEW

**Comment by BigRoy** [comment]
Is there any family type we **do** support in Apprentice? :) Like, are we better off just saying "don't use apprentice"?

**Comment by MustafaJafar** [comment]
> Is there any family type we **do** support in Apprentice? :) Like, are we better off just saying "don't use apprentice"?

It's much easier saying "don't use apprentice". 
personally, as long as Houdini support them, then it's fair to allow users to publish them. 
God knows, maybe Ayon would be used in educational institutes that run apprentice, or studios that want to examine/test workflows without acquiring a license.

**Comment by moonyuet** [comment]
> Is there any family type we **do** support in Apprentice? :) Like, are we better off just saying "don't use apprentice"?



> Is there any family type we **do** support in Apprentice? :) Like, are we better off just saying "don't use apprentice"?

vdb and bgeo supported in apprentice, review and render family also but there is some resolution limitation.

**Comment by BigRoy** [comment]
Fine with me then. :)

**Review by BigRoy — APPROVED** [review]
Fine with me.

I wonder if the actual `process()` logic of this plug-in becomes easier to parse if it were:

```
if not hou.isApprentice():
    return

... do the rest
```

But it shouldn't make a difference so I guess it's ok.

**Comment by moonyuet** [comment]
Work as expected
image
image

**Review by moonyuet — APPROVED** [review]

**Pull request merged**
