### PR TITLE
Publisher: Thumbnail widget enhancements

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Thumbnails widget in Publisher has new 3 options to choose from: Paste (from clipboard), Take screenshot and Browse. Clear button and new options are not visible by default, user must expand options button to show them.

## Additional info
~Icons can be changed. Animation is just "fancy" look. I've tried to put the icons next to each other, but thumbnail was hard to see and buttons could overflow out of widget range.~

We could make icons bigger and adjust size of expanded icons by size of widget to make sure they're visible all the time.

This PR is expanding https://github.com/ynput/OpenPype/pull/5415 .

Known issue: Multiscreen screenshot of screens with different scaling does not work correctly.

## Visuals
image
image

## Testing notes:
1. Open publisher
2. Try Browse
3. Try Take screenshot
4. Try Paste from clipboard (you must copy image content from somewhere)
5. Clear button should work as before

### CODE REVIEW

**Review by LiborBatek — APPROVED** [review]
Works ok for me.
image

Did test all scenarios...all good!

**Comment by iLLiCiTiT** [comment]
Changed to show icons all the time.

**Comment by mustafa-zarkash** [comment]
I made a quick test, it looks good!

**Review by mustafa-zarkash — APPROVED** [review]
I made a quick test, it looks good!
I've a small question, Does this affects the standalone publisher only?

**Comment by BigRoy** [comment]
> Does this affects the standalone publisher only?

It should affect all hosts.

**Pull request merged**
