### PR TITLE
Max: Implementation of Camera Attributes Validator

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
Implement Validate Camera Attributes in camera family in Max host

## Additional info
- This validator is not eligible for the camera created from the external plugins such as Redshift and Arnold etc.
- When the values of the camera attributes in the setting set to 0, the validator would skip checking the attribute.

## Testing notes:
1. Launch Max via launcher
2. Tweak the settings `ayon+settings://max/publish/ValidateCameraAttributes` or `project_settings/max/publish/ValidateCameraAttributes`
image
image
3. Create Camera Instance
4. Publish
5. If the camera attributes dont align with those attributes in the setting, the validator would error out.

### CODE REVIEW

**Comment by LiborBatek** [comment]
When tested with ```Near``` and ```Far``` ranges for enviro and clipping I have been able to ```Publish``` camera successfully even with wrong values...maybe when not turned on those checkers for ```Show``` and ```Clip Manually``` ??

Screenshot 2024-01-09 103936

 however next time trying publishing the ```Validator``` kicked in correctly but again the messaging could be strongly improved imho


Screenshot 2024-01-09 104329

**Comment by moonyuet** [comment]
> Not sure whats the origin of this PR but right now as we have it theres is no way to `validate` just a few of the values but `all` together.... theres no way to selectively choose what to validate or at least to disable particular value?
> 
> Maybe would be option to use `0` `Value` to disable each entry? Something like validating against zero means `skip this value in validation` ??
> 
> image

 the initial purpose of this PR is to build the Camera Attributes validator in Max which is similar to Maya. But the Maya one is more hard-coded and I am not sure it will be good idea for Max. But I agree with you that we can just skip the check when the parameter set to zero

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Im getting validate errors even when my values set on the ```camera``` matches the ```validator```....

Screenshot 2024-01-10 115432

When I remove the ```Camera``` Instance and recreate it from scratch it suddenly works as expected and ```validate``` correctly.

Screenshot 2024-01-10 115627

**Comment by moonyuet** [comment]
@LiborBatek I have updated the commit and the changelog.
The validation should check if the camera attributes aligning with the settings.
You may find the video below helpful.

https://github.com/ynput/OpenPype/assets/64118225/5c1b972f-a6be-4996-82e7-21945b6e5ee3

Do you think that it's also good idea to add repair action for the camera attributes?

**Comment by LiborBatek** [comment]
> Do you think that it's also good idea to add repair action for the camera attributes?

Yeah would be nice! ...Did u manage to incorporate those ```zero``` values for skipping the ```validation``` or not yet?

**Comment by moonyuet** [comment]
> Yeah would be nice! 

Okay I will add it into the next commit

> .Did u manage to incorporate those `zero` values for skipping the `validation` or not yet?

Yes, it was already there in the updated commit.

**Review by LiborBatek — CHANGES_REQUESTED** [review]
Screenshot 2024-01-11 132306

I have tested all sort of combinations of values used for validation and my findings so far being:

- Repair Func works as expected
- Validators set to ```0``` arent taken into account as expected
- Values used for validation being in ```generic``` units which is ok but will give different value after ```Repair``` action if users scene being in different ```unit system``` - if switched later afterwards the values matches properly. 
- Entering values for ```Near Range: 0.1``` and ```Far Range: 999.5``` wont pass ```Validate```

So there are 2 issues now, question being if we should take into account Scene Units or just note it in the OP Settings via docstring that those Values being in ```generic units``` and some conversion gonna happen if not using the same.

The Validation issue seems tied to the numbers format and invalid logic for decimal values?? Now just guessing tho.

**Comment by moonyuet** [comment]
> So there are 2 issues now, question being if we should take into account Scene Units or just note it in the OP Settings via docstring that those Values being in `generic units` and some conversion gonna happen if not using the same.
> 

Yes I think we can mention that those default values are being in `generic units` in both settings and validators, so that the user can change the value as their own default in regard to what they set in scene units. (we can possibly add one more check on the scene units to give this message too)

> The Validation issue seems tied to the numbers format and invalid logic for decimal values?? Now just guessing tho.

I need to double check, it is supposed that it tied to the float format.

**Review by LiborBatek — APPROVED** [review]
Now it all works fine! Even when having values for validating like

```0.1``` and ```999.5```

```Repair``` function also works as expected and when using ```zero value``` in the OP Settings it correctly ignores / skip ```Validation```.

image

**Comment by mkolar** [comment]
Looks good for merge. @moonyuet port to ayon pls

**Comment by moonyuet** [comment]
> Looks good for merge. @moonyuet port to ayon pls

Already ported to ayon-core!

**Pull request merged**
