### PR TITLE
AYON workfiles tools: Revisit workfiles tool

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Revisited workfiles tool for AYON mode to reuse common models and widgets.

## Additional info
Reused models and widgets from `ayon_utils`. Button "Go to current context" works. Refresh button refreshes workfiles too.

## Testing notes:
1. Launch DCC/host of your choice
2. Open workfiles tool
3. Try few standard things with workfiles tool
- Try to open/save workfiles
- Change context and open/save
- Save artist note
- Open published file
- Copy published file
- Hit refresh (should refresh all folders, tasks and workfiles)

### CODE REVIEW

**Comment by BigRoy** [comment]
I saw [this commit](https://github.com/ynput/OpenPype/pull/5897/commits/2d52e7f5a3cdbe8b9f1187c9aa68de206c1b340a) - I think that's nice ❤️ but was just wondering whether this was implemented to resolve certain bugs or issues? I'm asking because it's totally possible to save new files without the work files tool which might not have the info stored regardless of whether the workfiles tool would have done so.

**Review by kalisp — APPROVED** [review]
Tested in PS, AE, works.

**Comment by kalisp** [comment]
Mmt, retesting...

**Comment by kalisp** [comment]
Actually I found two issues, one warning after Workfiles dialog shows up:

AnyDesk_5gkIRr5rp6

and secondary  when file is saved:
image

**Comment by iLLiCiTiT** [comment]
> Actually I found two issues, one warning after Workfiles dialog shows up: (in AE)

Strange, that code didn't change in this PR.

**Review by 64qam — APPROVED** [review]
working in Nuke, PS, AE

**Pull request merged**
