### PR TITLE
added missing "custom" section from the ocio config

### PR DESCRIPTION
**Pull request by rontown**
Was causing a major break when using custom ocio conf packages in nuke

### CODE REVIEW

**Comment by jakubjezek001** [comment]
Hey @rontown, thanks for your input!

A few versions ago, we removed a certain feature. We did this because we now use the OCIO environment variable workflow. Once it's set and Nuke recognizes it during bootstrap, it completely overrides any options.

The custom option has to be linked with the cutstomOCIOConfigPath root knob. But since the OCIO workflow was overriding it, there was no need to keep those knob configs.

More info can be found here [colorspace docs](https://ayon.ynput.io/docs/admin_colorspace)

**Comment by jakubjezek001** [comment]
explained here https://github.com/ynput/OpenPype/pull/5900#issuecomment-1814316046

**Comment by rontown** [comment]
Thanks for the feedback. 
I guess it's not exactly clear in the docs, or you aren't testing it in the way which is used in production. 

Currently when setting the an ocio custom path/config file on the ayon server this doesn't work when loading nuke, as nuke requires the "custom" field to be selected in order to use the env var ocio set from the server. 
This is causing immediate and major breaks in nukes colour workflow.

Perhaps the team would require some additional experienced compositor testing/feedback on issues like these of which I'm happy to help.

**Comment by jrsndl** [comment]
> Currently when setting the an ocio custom path/config file on the ayon server this doesn't work when loading nuke, as nuke requires the "custom" field to be selected in order to use the env var ocio set from the server.

Can you please share the OS and Nuke version that demonstrates the issue? I do not se it in Nuke 14 + Windows 10

**Comment by rontown** [comment]
Nuke 14.0v6 and Windows 10. If custom isn't selected in the nuke colour settings this will have the same effect in any Nuke version and OS.

**Pull request closed without merging**
