### PR TITLE
Nuke: Update camera node type to Camera3 as Camera2 is deprecated in Nuke 15

### PR DESCRIPTION
**Pull request by fabiaserra**
## Testing notes:
1. Load a camera in OP and try render it out in Nuke 15

### CODE REVIEW

**Comment by jakubjezek001** [comment]
@moonyuet didn't we do this fix already?

**Comment by moonyuet** [comment]
> @moonyuet didn't we do this fix already?

we fixed the one in the creator but not the loader

**Comment by jakubjezek001** [comment]
here is related PR I am talking about https://github.com/ynput/OpenPype/pull/6118

**Comment by moonyuet** [comment]
> here is related PR I am talking about #6118
> 
> Perhaps it would be better to implement it it the way @fabiaserra

Agreed. It is safer to implement the function of camera creations which supports different nuke versions.

**Comment by fabiaserra** [comment]
And are you sure we want `Camera4` instead of `Camera3`? My artists said they wanted `Camera3`

**Comment by mkolar** [comment]
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be re-created to target one of those.

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-core](https://github.com/ynput/ayon-core) or the host addon repository once it's up.

**Pull request closed without merging**
