### PR TITLE
Houdini: fix typo error in collect arnold rop

### PR DESCRIPTION
**Pull request by mustafa-zarkash**
## Changelog Description
Fixing a typo error in `collect_arnold_rop.py`

Reference: [#5280](https://github.com/ynput/OpenPype/issues/5280)

### CODE REVIEW

**Review by BigRoy — APPROVED** [review]
Seemed to be a typo indeed - didn't test but this change makes sense.

**Comment by BigRoy** [comment]
> I dont have arnold for Houdini installed (as it needs to be paid), but the code looks good for me.

I believe you should be able to run `mtoa` and `htoa`, etc. without a license - you just won't be able to do (final) renders. I believe you can even render with a watermark if no license is available.

**Comment by moonyuet** [comment]
> > I dont have arnold for Houdini installed (as it needs to be paid), but the code looks good for me.
> 
> I believe you should be able to run `mtoa` and `htoa`, etc. without a license - you just won't be able to do (final) renders. I believe you can even render with a watermark if no license is available.

didn't realize that arnold does have skip license check in htoa too.... I thought they only allow maya to do the rendering with skipping license check but I was wrong! ANd you can do final rendering but with the watermark too.

**Review by moonyuet — APPROVED** [review]
image
Looks good with the test

**Comment by BigRoy** [comment]
@antirotor @mkolar ready to merge! :)

**Pull request merged**
