### PR TITLE
AYON: General fixes and updates

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Changelog Description
Few smaller fixes related to AYON connection. Some of fixes were taken from [this PR](https://github.com/ynput/OpenPype/pull/4959/files).

## Additional info
Fix of tools attribute conversion on project and asset. Fix representation fields conversion. Fix `get_last_version_by_subset_id` function. Convert maya load colors. Fix missing variable in maya lib function.

## Testing notes:
1. start with this step
2. follow this step

### CODE REVIEW

**Review by tokejepsen — CHANGES_REQUESTED** [review]
Loader in Maya 2020 fails with:

```
Fetching asset..
#   File "C:\Users\tokejepsen\OpenPype\openpype\tools\utils\lib.py", line 723, in run
# Traceback (most recent call last):
#   File "C:\Users\tokejepsen\OpenPype\openpype\tools\loader\model.py", line 449, in _fetch
#     func(*args, **kwargs)

type object 'datetime.datetime' has no attribute 'fromisoformat': # AttributeErrorcreated_at = datetime.datetime.fromisoformat(version["createdAt"])
#     #   File "C:\Users\tokejepsen\OpenPype\openpype\client\server\conversion_utils.py", line 569, in convert_v4_version_to_v3
versions.append(convert_v4_version_to_v3(version))
#     #   File "C:\Users\tokejepsen\OpenPype\openpype\client\server\entities.py", line 131, in _get_versions
fields=fields
#     #   File "C:\Users\tokejepsen\OpenPype\openpype\client\server\entities.py", line 377, in get_last_versions
fields=["_id", "parent", "name", "type", "data", "schema"]
#     #   File "C:\Users\tokejepsen\OpenPype\openpype\tools\loader\model.py", line 449, in _fetch
func(*args, **kwargs)
#     #   File "C:\Users\tokejepsen\OpenPype\openpype\tools\utils\lib.py", line 723, in run
# Traceback (most recent call last):
# AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
#     created_at = datetime.datetime.fromisoformat(version["createdAt"])
#   File "C:\Users\tokejepsen\OpenPype\openpype\client\server\conversion_utils.py", line 569, in convert_v4_version_to_v3
#     versions.append(convert_v4_version_to_v3(version))
#   File "C:\Users\tokejepsen\OpenPype\openpype\client\server\entities.py", line 131, in _get_versions
#     fields=fields
#   File "C:\Users\tokejepsen\OpenPype\openpype\client\server\entities.py", line 377, in get_last_versions
#     fields=["_id", "parent", "name", "type", "data", "schema"]
```

**Comment by BigRoy** [comment]
Regarding [this error](https://github.com/ynput/OpenPype/pull/4975#pullrequestreview-1430163873) -> [`datetime.fromisoformat` is Py 3.7+ only](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat)

**Comment by iLLiCiTiT** [comment]
> Also note that the error doesn't seem to be introduced with this PR but existed prior to it it seems?

It does not, but in this case I agree it should be fixed here.

**Comment by iLLiCiTiT** [comment]
Nevermind, it requires bigger changes. Definetelly for different PR.

**Review by tokejepsen — APPROVED** [review]
Tested in Maya 2023 succesfully.

**Pull request merged**
