### PR TITLE
Batch script for running Openpype on Deadline.

### PR DESCRIPTION
**Pull request by tokejepsen**
## Description
Helps with development of render farm features by not having to build executable of openpype_console on Windows.

## Testing notes:
1. Add/replace `OpenPype Executable` in Deadline OpenPype plugin settings.
2. Submit render to Deadline.

### CODE REVIEW

**Comment by kalisp** [comment]
Could some basic documentation be added to the file, please?

**Comment by tokejepsen** [comment]
> Could some basic documentation be added to the file, please?

Sure, in what format? As a bulk comment or some `help` flag?

**Comment by kalisp** [comment]
Just comments, similar to in existing .ps1 or .sh scripts.

**Comment by tokejepsen** [comment]
> Just comments, similar to in existing .ps1 or .sh scripts.

done

**Comment by kalisp** [comment]
Problem with this is that it still search for required version, as I understand it would work only if version env var is removed from job.

**Comment by antirotor** [comment]
Could we also add *nix shell version?

**Comment by tokejepsen** [comment]
> Could we also add *nix shell version?

Maybe for a different PR?
I've had a need for this, while testing farm rendering but if there is no need for Unix developers then dont invest the time?
I couldn't make Unix shell versions anyways as I'm on Windows.

**Comment by tokejepsen** [comment]
> Problem with this is that it still search for required version, as I understand it would work only if version env var is removed from job.

@kalisp I've made this PR to tackle that issue; https://github.com/ynput/OpenPype/pull/4489

**Review by kalisp — APPROVED** [review]
Works.

**Comment by mkolar** [comment]
Sounds like we can merge it?

**Pull request merged**
