### PR TITLE
Documentation: API docs reborn - yet again

### PR DESCRIPTION
**Pull request by antirotor**
## Feature

Add functional base for API Documentation using Sphinx and AutoAPI.

After unsuccessful #2512, #834 and #210 this is yet another try. But this time without ambition to solve the whole issue. This is making Shinx script to work and nothing else. Any changes and improvements in API docs should be made in subsequent PRs. 

## How to use it

You can run:

```sh
cd .\docs
make.bat html
```

or 

```sh
cd ./docs
make html
```

This will go over our code and generate **.rst** files in `/docs/source/autoapi` and from those it will generate full html documentation in `/docs/build/html`.

During the build you'll see tons of red errors that are pointing to our issues:

1) **Wrong imports**
    Invalid import are usually wrong relative imports (too deep) or circular imports.

2) **Invalid doc-strings**
   Doc-strings to be processed into documentation needs to follow some syntax - this can be checked by running 
   `pydocstyle` that is already included with OpenPype
3) **Invalid markdown/rst files**
    md/rst files can be included inside rst files using `.. include::` directive. But they have to be properly formatted.

## Editing rst templates

Everything starts with `/docs/source/index.rst` - this file should be properly edited, Right now it just includes `readme.rst` that in turn include and parse main `README.md`. This is entrypoint to API documentation. All templates generated by AutoAPI are in `/docs/source/autoapi`. They should be eventually commited to repository and edited too.

## Steps for enhancing API documentation

1) Run `/docs/make.bat html`
2) Read the red errors/warnings - fix it in the code
3) Run `/docs/make.bat html` again until  there are not red lines
4) Edit rst files and add some meaningfull content there

> **Note**
> This can (should) be merged as is without doc-string fixes in the code or changes in templates. All additional improvements on API documentation should be made in new PRs.

> **Warning**
> You need to add new dependencies to use it. Run `create_venv`.

Connected to #2490

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
Got error:
```
Extension error:
Could not import extension autoapi.extension (exception: No module named 'autoapi')
```

**Comment by antirotor** [comment]
> Got error:
> 
> ```
> Extension error:
> Could not import extension autoapi.extension (exception: No module named 'autoapi')
> ```

Should be fixed by making autoapi mandatory. I knew I shouldn't have play with it :)

**Comment by Minkiu** [comment]
Hey, tried on Linux and I had to:
1) Create a venv and activate
2) Install the following packages: 
`pip install sphinx sphinx-autoapi myst-parser linkify-it-py https://github.com/revitron/revitron-sphinx-theme/archive/master.zip`

3)
```
build succeeded, 1051 warnings.

The HTML pages are in build/html.

```

Maybe we could add a README.md for a simpler "just build the docs"

**Review by Minkiu — APPROVED** [review]

**Comment by antirotor** [comment]
> 1. Create a venv and activate
> 2. Install the following packages:
>    `pip install sphinx sphinx-autoapi myst-parser linkify-it-py https://github.com/revitron/revitron-sphinx-theme/archive/master.zip`

That's strange, Poetry should take care of it. By running `./tools/create_env.sh` it should update the venv with exactly those!

> Maybe we could add a README.md for a simpler "just build the docs"

Yep, README.md with these would definitely help, I'll add it.

**Comment by jakubjezek001** [comment]
Isn't this ready to be merged?

**Comment by mkolar** [comment]
I thin it is, but @antirotor is the who should pull the trigger.

**Comment by antirotor** [comment]
> Isn't this ready to be merged?

I just wanted to add a readme.md with some info about building the documentation

**Pull request merged**
