### PR TITLE
Missing nuke family Windows arguments

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
Default Windows arguments for launching the Nuke family was missing.

## Testing notes:
1. Setup AYON with default settings for applications.
2. Launch Hiero/NukeAssist/NukeStudio.

### CODE REVIEW

**Comment by iLLiCiTiT** [comment]
@m-u-r-p-h-y  I think they should be added to other platforms too? Aren't they missing in AYON settings too?

**Comment by tokejepsen** [comment]
@m-u-r-p-h-y not sure how it works on Mac and Linux. Should I just add the same arguments to all platforms?

**Comment by iLLiCiTiT** [comment]
> Should I just add the same arguments to all platforms?

Probably skip darwin, it has `NukeAssist.xxx.app` executable.

**Comment by tokejepsen** [comment]
> I think they should be added to other platforms too? Aren't they missing in AYON settings too?

Done

**Review by jakubjezek001 — APPROVED** [review]

**Review by iLLiCiTiT — APPROVED** [review]
LGTM

**Pull request merged**
