### PR TITLE
Publisher: Add more options to thumbnail widget

### PR DESCRIPTION
**Pull request by BigRoy**
## Changelog Description

Add more options to thumbnail widget like "Browse..." and "Set image from clipboard"

## Additional info

This is a bit of a quick and dirty prototype for the extra options.

**Note**: For current draft I've used an existing image in the repo (minus) which **is not a very good icon choice** - but I wasn't sure where you were getting the icon PNGs from @iLLiCiTiT so wasn't sure how to best get horizontal three dots icon for "More options" or alike.

How it looks now:
image
image
image

@fabiaserra thoughts?

## Testing notes:

1. Run publisher, use the different 'set thumbnail' options.

### CODE REVIEW

**Comment by BigRoy** [comment]
Instead of a menu we could add extra buttons like:

**Set From clipboard**


**Browse icon**


But I feel it'd quickly start cluttering it up even more and I'm not sure it'd be very clear to the artist either.

**Comment by iLLiCiTiT** [comment]
I just found out this PR and I've already started to work on UI how to show other options (it contains animations 😎 ).

**Comment by iLLiCiTiT** [comment]
Animation

**Comment by BigRoy** [comment]
It looks pretty, but I am not sure whether I like it more than having the button show just show a menu with text and icons. The icons currently are small (which makes it look tidy) but I can definitely see people not directly knowing what each icon is for.

Love to know what others think though.

**Comment by fabiaserra** [comment]
I like it! The icons + tooltips seem clear enough to me

**Comment by BigRoy** [comment]
I'd say - let's deploy it and let's see how the community responds? It's definitely flashy! ❤️

**Pull request closed without merging**
