### PR TITLE
fix the bug of fbx loaders in Max

### PR DESCRIPTION
**Pull request by moonyuet**
## Changelog Description
bug fix of fbx loaders for not being able to parent to the CON instances while importing cameras(and models) which is published from other DCCs such as Maya.

## Additional info
n/a

## Testing notes:
1. Launch Max via Openpype
2. Click "Load...."
3. Load Camera/Model Instance which is published from other DCCs such as maya
4. Also try to load Camera/Model Instance which is published within 3dsMax.
5. Both should free with error shown in the log in 3dsMax

### CODE REVIEW

**Review by LiborBatek — COMMENTED** [review]
The ```Load``` works ok in general.

Problem being wrong Y axis orientation caused by different coord system in Maya (Y up).
Could be just setting the option in FBX importer.

The highlighted Camera is wrong oriented and the blue one being correct (originated from Alembic)
image

**Comment by moonyuet** [comment]
> The `Load` works ok in general.
> 
> Problem being wrong Y axis orientation caused by different coord system in Maya (Y up). Could be just setting the option in FBX importer.
> 
> The highlighted Camera is wrong oriented and the blue one being correct (originated from Alembic) image

I updated the PR, the axis should be fixed!

**Review by antirotor — APPROVED** [review]
code seems great!

**Review by LiborBatek — APPROVED** [review]
Now all works as it should.

The camera in FBX perfectly matches the Alembic representation.

image

**Pull request merged**
