### PR TITLE
Testing: Ingest expected database

### PR DESCRIPTION
**Pull request by tokejepsen**
## Changelog Description
This ingests the expected database in a json format. The testing of the database has been changed to compare against the expected json file rather than hardcoded counts of database entities. This should allow anyone to update the expected database json without needed to update the testing code.

Split from #5644

## Testing notes:
```
openpype_console runtests C:\Users\tokejepsen\OpenPype\tests\integration\hosts\maya --mongo_url "mongodb://localhost:2707/"
```

### CODE REVIEW

**Comment by tokejepsen** [comment]
Pending deadline testing expected database.

**Comment by kalisp** [comment]
I don't see benefit of this at all. Either I need to edit test class or json, I'll need to do commit either way.

Explicit counts in test server as a some kind of documentation of "if I have this workfile and I'll publish it, I expect X representations, with this names". Comparisons of json loose that, imho.

**Comment by tokejepsen** [comment]
> I don't see benefit of this at all. Either I need to edit test class or json, I'll need to do commit either way.

For a developer, I agree it does not matter whether you edit the test class or json, but for a non-developer editing the test class is quite a learning curve. Instead of needing to know Python/Git to update the tests, a non-developer can just dump the databases after updating the workfile and commit. Means a non-developer does not need to know Python to make tests.

What do you think about that?

**Comment by tokejepsen** [comment]
https://github.com/ynput/OpenPype/pull/5961#issuecomment-1846979590

@kalisp could I get your opinion on this before I look at this PR again?

**Comment by mkolar** [comment]
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be re-created to target one of those.

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-core](https://github.com/ynput/ayon-core) or the host addon repository once it's up.

**Pull request closed without merging**
